### ISSUE TITLE
rog.asus.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#1013]
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
The cookie Pop-Up is hidden. But overlay doesn't look normal. Is it possibel to polish it?
#### 🔗 URL
https://rog.asus.com/de/motherboards/rog-crossblade/rog-crossblade-ranger-model/helpdesk_download/
#### 🏷️ Version
7.3.0

**Comment by sonnyxq** [comment]
![Screenshot 2024-09-20 221957](https://github.com/user-attachments/assets/d86922e5-f509-46fc-9ae7-793c69a10579)
