### ISSUE TITLE
thetvdb.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#1018]
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://thetvdb.com/
#### 🏷️ Version
7.3.0

**Comment by wanhose** [comment]
Same as #992.

**Comment by sonnyxq** [comment]
@wanhose Hi.

I am not able to scroll up and down.
Until I turn off the extension.
Modify the invisible pop-up...
Then website works.

![Screenshot 2024-10-06 193214](https://github.com/user-attachments/assets/71cbc8e1-bed3-4e91-935c-2238ec5df762)

**Comment by wanhose** [comment]
> @wanhose Hi.
> 
> I am not able to scroll up and down. Until I turn off the extension. Modify the invisible pop-up... Then website works.
> 
> ![Screenshot 2024-10-06 232653](https://private-user-images.githubusercontent.com/60904977/373981158-6016f3e5-194d-41e3-a574-a5c83b0ed4ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyOTYwNDAsIm5iZiI6MTcyODI5NTc0MCwicGF0aCI6Ii82MDkwNDk3Ny8zNzM5ODExNTgtNjAxNmYzZTUtMTk0ZC00MWUzLWE1NzQtYTVjODNiMGVkNGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDEwMDkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZDYzNDkyNzg5ZDE4MzdmNDVjZDUzMTk2YTAyODhlY2I0ZmRmMWMzNmZhYjFhODQzZTY5ZmI2MjgzMWQxYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Tv1dgJjtR3LMU_q3NLXeZifvPlkNIQv7l7VzGxVlBr0)

Hi @sonnyxq,

Please, update your database version to `>= 1728296484406`.

Thanks!
