### ISSUE TITLE
naturitas.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#1041]
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
You can't use the page until deactivate extension and modify cookies.
#### 🔗 URL
https://www.naturitas.de/
#### 🏷️ Version
7.3.0

**Comment by sonnyxq** [comment]
On:
![Screenshot 2024-09-20 230807](https://github.com/user-attachments/assets/507d3174-2ca5-4737-9b67-b99d68f44942)

Off:
![Screenshot 2024-09-20 230820](https://github.com/user-attachments/assets/a95453e0-6183-4462-b95e-84f92615be02)

**Comment by wanhose** [comment]
> On: ![Screenshot 2024-09-20 230807](https://private-user-images.githubusercontent.com/60904977/369554624-507d3174-2ca5-4737-9b67-b99d68f44942.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDY5NTcsIm5iZiI6MTcyNzk0NjY1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjk1NTQ2MjQtNTA3ZDMxNzQtMmNhNS00NzM3LTliNjctYjk5ZDY4ZjQ0OTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA5MTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMTI1MzVmOWVlMThmNTAxOGE5N2IxYzI1MDNhZTBiZDRiNDIwMTI0NzA0NmVlYzI1YzZmNjZmNjE2Y2U0YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rgf8XG3A9k7POKfa0niw6MxgPmaw0CALMDBsRS1ytwQ)
> 
> Off: ![Screenshot 2024-09-20 230820](https://private-user-images.githubusercontent.com/60904977/369554641-a95453e0-6183-4462-b95e-84f92615be02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDY5NTcsIm5iZiI6MTcyNzk0NjY1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjk1NTQ2NDEtYTk1NDUzZTAtNjE4My00NDYyLWI5NWUtODRmOTI2MTViZTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA5MTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmY2MzMWYyZTg4YzNiMzRlZDhjMDcwMDljMjM1YjA1MTAyNjI2Y2E0YjU3ZjVlMzhlZTA2YjBhNTk3ZWU4NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.saQOAKxCdzA0ZUzKtO0-j4heoZtdUL7lhLSAATBEUg0)

Hi @sonnyxq,

Please, update to database version `>= 1727946733065`.

Thanks!
