### ISSUE TITLE
veed.io

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#1042]
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
Blank page.
#### 🔗 URL
https://www.veed.io/tools/video-compressor
#### 🏷️ Version
7.3.0

**Comment by sonnyxq** [comment]
On:
![Screenshot 2024-09-20 231243](https://github.com/user-attachments/assets/3a51c31a-1f13-4678-9246-a3e78bacf01f)

Off:
![Screenshot 2024-09-20 231253](https://github.com/user-attachments/assets/6345435c-de69-4e8b-8309-fd1d46ec3ff3)

**Comment by wanhose** [comment]
> On: ![Screenshot 2024-09-20 231243](https://private-user-images.githubusercontent.com/60904977/369555462-3a51c31a-1f13-4678-9246-a3e78bacf01f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDk2NzgsIm5iZiI6MTcyNzk0OTM3OCwicGF0aCI6Ii82MDkwNDk3Ny8zNjk1NTU0NjItM2E1MWMzMWEtMWYxMy00Njc4LTkyNDYtYTNlNzhiYWNmMDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA5NTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZmU3NTVlZWRkNWZhZDUwMGEwNzRjYmY1NGQ1Y2M5MzYwYjI5MDU4NzdiOGQ3MzllN2QxYjRiN2YxNDlhNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.lhU8ZZa2E4_cUSm2xhwkX_KUYOoRrTgnWz1C3rufg9Q)
> 
> Off: ![Screenshot 2024-09-20 231253](https://private-user-images.githubusercontent.com/60904977/369555468-6345435c-de69-4e8b-8309-fd1d46ec3ff3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDk2NzgsIm5iZiI6MTcyNzk0OTM3OCwicGF0aCI6Ii82MDkwNDk3Ny8zNjk1NTU0NjgtNjM0NTQzNWMtZGU2OS00ZThiLTgzMDktZmQxZDQ2ZWMzZmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA5NTYxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NGUxYTdmOGM4OWJlNjg1NmY1YzI1YzNjZjIxNWRiMDk0NzlkYTY3YTc2NTUwMWI1ZTRjYjczNTc0MDU0ZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TGhCPX5pbB6X6UzPWbNTgxzvOyWUZ3SUetXVrbvz3JQ)

Hi @sonnyxq,

Please, update to database version `>= 1727690050265`.

Thanks!
