### ISSUE TITLE
flexispot.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#1048]
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
Extension breaks it. Its needed to be deactivated. Configure. Then action.
#### 🔗 URL
https://www.flexispot.de/backsupport-burostuhl-bs5.html
#### 🏷️ Version
7.3.0

**Comment by sonnyxq** [comment]
On:
![Screenshot 2024-09-22 051333](https://github.com/user-attachments/assets/f6f005e9-92f2-4c3b-95d3-578f4da298e5)

Off:
![Screenshot 2024-09-22 051347](https://github.com/user-attachments/assets/51602763-69fc-4c2a-ad19-e04c02d0487a)

**Comment by wanhose** [comment]
> On: ![Screenshot 2024-09-22 051333](https://private-user-images.githubusercontent.com/60904977/369662074-f6f005e9-92f2-4c3b-95d3-578f4da298e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTQ0OTcsIm5iZiI6MTcyNzk1NDE5NywicGF0aCI6Ii82MDkwNDk3Ny8zNjk2NjIwNzQtZjZmMDA1ZTktOTJmMi00YzNiLTk1ZDMtNTc4ZjRkYTI5OGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDExMTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZjdhMjljM2IxYzg5NmM4NDlkNjg5MWQ0ZjUyYWM5NDFjMzNiMDhlOTk2NDI3YjA4MTJiZDY3YTdmY2M4MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PsK1L6e21G0-YpmqZjjbcZ732KdjjKCURUVKc9I-iY4)
> 
> Off: ![Screenshot 2024-09-22 051347](https://private-user-images.githubusercontent.com/60904977/369662076-51602763-69fc-4c2a-ad19-e04c02d0487a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTQ0OTcsIm5iZiI6MTcyNzk1NDE5NywicGF0aCI6Ii82MDkwNDk3Ny8zNjk2NjIwNzYtNTE2MDI3NjMtNjlmYy00YzJhLWFkMTktZTA0YzAyZDA0ODdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDExMTYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5ODhhZWI2ZGNhY2QyN2NmZjBkZjQ4MDI1N2U2YTNjOWY1NmNmZGIyMTA3MzQ2ZjJjNGMxYzc5MjlmMGRhNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LxDjFgOl5-qxpXPmWCDFrnDCG0BDDyb4aFka3yil_qk)

Hi @sonnyxq,

Please, update to database version `>= 1727954177335`.

Thanks!
