### ISSUE TITLE
chairgo.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#1049]
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
The cookie pop-up - which is invisible - breaks the website when you open up the picture and scroll up and down and the price is showing up.
#### 🔗 URL
https://www.chairgo.de/herman-miller-aeron-graphite-groesse-b-vinylpads/
#### 🏷️ Version
7.3.0

**Comment by sonnyxq** [comment]
On:
![Screenshot 2024-09-22 060943](https://github.com/user-attachments/assets/f9bf4bea-2ec7-4c31-bf5b-b525b38e7e8b)

Off:
![Screenshot 2024-09-22 061000](https://github.com/user-attachments/assets/8c4fff23-195b-4971-8e89-513fdd4739cd)

**Comment by wanhose** [comment]
> On: ![Screenshot 2024-09-22 060943](https://private-user-images.githubusercontent.com/60904977/369663943-f9bf4bea-2ec7-4c31-bf5b-b525b38e7e8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTQ2MTAsIm5iZiI6MTcyNzk1NDMxMCwicGF0aCI6Ii82MDkwNDk3Ny8zNjk2NjM5NDMtZjliZjRiZWEtMmVjNy00YzMxLWJmNWItYjUyNWIzOGU3ZThiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDExMTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmYmI2YzU5OGEzMWU1NzM0YmI1YjI5ZWEwNWI5MjlmMjlkY2JkMThiMjBmNGQ5NGM3MzEzYzM0NWI2ZWMzOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8sLkO7VStgsDrYTp_vgxNB0YuVTjh0baswH-OFfXd78)
> 
> Off: ![Screenshot 2024-09-22 061000](https://private-user-images.githubusercontent.com/60904977/369663944-8c4fff23-195b-4971-8e89-513fdd4739cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTQ2MTAsIm5iZiI6MTcyNzk1NDMxMCwicGF0aCI6Ii82MDkwNDk3Ny8zNjk2NjM5NDQtOGM0ZmZmMjMtMTk1Yi00OTcxLThlODktNTEzZmRkNDczOWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDExMTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmMjY5NDhjMjJmMTFjMDE5MzgzNWUzMjFhMTUzODkxNDE1OWEyN2I2MjczMzc3NDg5NGU5MGFiMjAwMjg4YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3Eyx1L-puf6vXJanWGCKj14wly3VslRsxhPxVV5Vww8)

Hi @sonnyxq,

Please, update to database version `>= 1727955012372`.

Thanks!
