### ISSUE TITLE
Incorrect translation (it)

### ISSUE THREAD

**Issue by marcoclg19** [wanhose/cookie-dialog-monster#133]
Hi, @wanhose. 
I am opening this issue because I have noticed that an Italian translation string of the extension is wrong.
The mistake is on **line 24** of the link below:
 https://github.com/wanhose/cookie-dialog-monster/blob/main/packages/browser-extension/src/_locales/it/messages.json

`"Não é possível clicar"` should be changed to `"Non è possibile cliccare"`.

Cheers!

**Comment by wanhose** [comment]
Hi @marcoclg19,

Thanks for your feedback, do you want to contribute to this project opening your first pull request about this issue? If not, I can do it soon.

Feel free to open more issues to improve the internationalization!

**Comment by marcoclg19** [comment]
> Hi @marcoclg19,
> 
> Thanks for your feedback, do you want to contribute to this project opening your first pull request about this issue? If not, I can do it soon.
> 
> Feel free to open more issues to improve the internationalization!

Just done! #137

**Comment by marcoclg19** [comment]
Sorry for asking... but when will the next release of the extension come out to see the correct string? :)

And another thing, (always if you want to answer) what is the difference of your project with IStillDontCareAboutCookies/Super Agent/Consent-O-Matic? I find your extension very nice!

**Comment by wanhose** [comment]
Hi @marcoclg19,

You will see your change before the end of this week! 😎 

Answering your question about the differences:

- **Consent-O-Matic** and **Super Agent** are very different solutions to this problem, they fill those dialogs based on your preferences. We don't accept/reject any dialog if not really needed (for example, if you can't pass to a page you want to see before accepting/rejecting). We always try to reject in this last case, if not we finally accept to make your experience as fast as possible.

- **I Still Dont Care About Cookies** is basically the most famous solution in the market, exactly a fork after Avast acquired it a few months ago. Our extension comes to give to the users a open source alternative with also a different approach: lighter, smarter and open source from day one.

- And finally **Cookie Dialog Monster** what I created following the best code practices, with only ~34KiB does a fantastic job in thousand of pages thanks to the huge database with almost 13000 entries and I think we have more regular updates than them.

Thanks for your comments, with your help we can do it better!

**Comment by marcoclg19** [comment]
> * **Consent-O-Matic** and **Super Agent** are very different solutions to this problem, they fill those dialogs based on your preferences. We don't accept/reject any dialog if not really needed (for example, if you can't pass to a page you want to see before accepting/rejecting). We always try to reject in this last case, if not we finally accept to make your experience as fast as possible.
> * **I Still Dont Care About Cookies** is basically the most famous solution in the market, exactly a fork after Avast acquired it a few months ago. Our extension comes to give to the users a, open source alternative with also a different approach: lighter, smarter and open source from day one.
> * And finally **Cookie Dialog Monster** what I created following the best code practices, with only ~34KiB does a fantastic job in thousand of pages thanks to the huge database with almost 13000 entries and I think we have more regular updates than them.
> 
> Thanks for your comments, with your help we can do it better!

Thanks for your helpful description. I usually use a DNS to block ads and the only thing that bothers me are the usual pop-up cookies. So, I was looking for the most suitable extension!

**Comment by wanhose** [comment]
New release in coming (https://github.com/wanhose/cookie-dialog-monster/releases/tag/6.2.2)!

Thank you so much @marcoclg19!
