### ISSUE TITLE
gazzetta.it

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#134]
## Specifications
- <b>Reason:</b> Popup showed up
- <b>URL:</b> https://www.gazzetta.it/
- <b>User-Agent:</b> Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
- <b>Version:</b> 6.2.1

**Comment by marcoclg19** [comment]
These cookie banners are the ones I can't tolerate! If you don't accept cookies they ask you to subscribe to the site.

**Comment by wanhose** [comment]
Hey @marcoclg19,

In this case, we need to add to `data/elements.txt` a new selector `.privacy-cp-wall`. This isn't the kind of dialog you say but I know what you say, they are the worst!

**Comment by marcoclg19** [comment]
> In this case, we need to add to `data/elements.txt` a new selector `.privacy-cp-wall`. 

If you want, I can experiment and tell you if it works. But I need more instructions :)

**Comment by marcoclg19** [comment]
The cookie pop-up of #135 is very similar to this. What do you think? @wanhose

**Comment by wanhose** [comment]
Regarding #135, I think they have different selectors but I need to take a look deeper 🤔

**Comment by marcoclg19** [comment]
> @marcoclg19 to test the new selectors locally, you need to copy the data folder inside `packages/browser-extension/src` and then use `chrome.getURL("data")` instead of our API URL in the background script.
> 
> But what I recommend you instead of this is to debug the nodes we get in `scripts/content.js` `match` function and look for the one you want to remove, then get its class or id attribute and then create a new entry in `data/elements.txt` for it.

Too complicated for me XD
