### ISSUE TITLE
No work here

### ISSUE THREAD

**Issue by happysurf** [wanhose/cookie-dialog-monster#14]
No work here on https://www.tuttotech.net/news/2021/07/25/oppo-watch-2-immagini-leak.html
https://www.tuttoandroid.net/news/2021/07/26/spotify-nuova-funzionalita-whats-new-902313/
Thanks!

**Comment by wanhose** [comment]
Hi @happysurf! Here we go https://github.com/wanhose/do-not-consent/commit/b5920b5cba844d7619a7403999521ab4a97a1d32 🚀

**Comment by wanhose** [comment]
Hi @happysurf! Here we go with [this new release (4.3.1)](https://github.com/wanhose/do-not-consent/releases/tag/4.3.1) 🚀

If you are using Mozilla Firefox you can update your extension right now because the update is uploaded but if you are using Google Chrome (or another Chromium based browser) you have to wait two or three hours because the update is pending for review by the Google guys.

If you still have any issues, feel free to open more threads 😄

**Comment by happysurf** [comment]
Also here:
https://www.marieclaire.com/it/bellezza/celebrity-beauty/a35201876/lady-diana-mascara-blu/

**Comment by wanhose** [comment]
Hi again @happysurf!

I have managed to fix **glitterphoto** site but **canva** is generating random attributes (making impossible to remove these elements without breaking other sites). About **marieclaire** site, it's working for me, can you tell me more about the problem in this page attaching screenshots, your current version and you know.

Thanks a lot for your feedback 🙂

**Comment by happysurf** [comment]
Today, the Marieclaire site, works fine also for me in Firefox 91 final version.
Thanks for your work!

**Comment by happysurf** [comment]
https://www.corriere.it/

**Comment by M1Aston** [comment]
https://twitter.com/
https://www.deepl.com/translator
https://www.autoblog.nl/
https://www.weeronline.nl
https://www.buienalarm.nl
https://www.geenstijl.nl
https://www.thegatewaypundit.com


Several newspapers belonging to the same company have a particularly nasty cookie message\page. Here are two examples (there are more):
https://www.destentor.nl/
https://www.ad.nl/
This is the cookie page:
https://myprivacy.dpgmedia.nl

**Comment by wanhose** [comment]
Hi again @happysurf, I can't see the dialog in https://www.corriere.it/ 😅

**Comment by wanhose** [comment]
Welcome aboard @M1Aston, I updated the database with new selectors that will fix everything related to first paragraph's pages but I can't see what's wrong with https://www.destentor.nl/ and https://www.ad.nl/ 😅

Thanks a lot for your effort reporting these pages.

**Comment by M1Aston** [comment]
Thanks for your kind welcome.
Here is an example to show you how loading the newspaper websites get stuck at the  "cookie page". I hope this helps.
![cookie](https://user-images.githubusercontent.com/43113612/132135310-e0dcfc28-dfdf-418b-9b6b-468605af517d.jpg)

**Comment by wanhose** [comment]
Hi again @M1Aston, these kind of pages are "preview" pages that redirect you to the final page when you accept their terms. I think we can't do anything in these cases. You can disable this extension to allow yourself accept their terms and later you will be redirect to the final page.

**Comment by M1Aston** [comment]
On some websites it makes scrolling impossible. Here is an example:
https://www.hema.nl/

**Comment by wanhose** [comment]
Fixed in [5.0.2](https://github.com/wanhose/cookie-dialog-monster/releases/tag/5.0.2)! Thank you for your feedback @M1Aston!

**Comment by M1Aston** [comment]
Thank you very much.
Bumped into another problem; Video playback doesn't work for the biggest Dutch newspaper when enabled. The video windows simply stays "black".
https://www.telegraaf.nl/video/

**Comment by wanhose** [comment]
Amazing feedback @M1Aston! I was testing this behavior and it seems that they have installed a script to load video components after you accepted your preferences. The only solution is accept their cookies 😅

**Comment by wanhose** [comment]
Hello again @M1Aston! Exactly the same as [https://www.telegraaf.nl](https://www.telegraaf.nl). You have to accept their cookies to turn on video playback 😅

**Comment by M1Aston** [comment]
Doesn't work here:
https://www.blikopnieuws.nl/

Disables normal functioning of page here:
https://www.automobielmanagement.nl/

**Comment by wanhose** [comment]
Hi @M1Aston, what version are you using? I released a few days ago the 5.2.0 version with a lot of improvements. Both pages are working correctly for me with 5.2.0.

**Comment by wanhose** [comment]
@M1Aston I think https://www.blikopnieuws.nl will be fixed if you upgrade to 5.2.0. About https://www.automobielmanagement.nl will be fixed in the next release because I need to research more.

Thank you for your feedback! 🙂

**Comment by M1Aston** [comment]
Thanks very much.
I'll try to report more international websites instead of just Dutch from now on. :-)

**Comment by wanhose** [comment]
Don't worry @M1Aston, the idea is exactly that, have people around the world contributing to this project from their own contexts. I will add a context menu button to Chrome to report easily those pages (but first, I have to create an API for this purpose or find a service) in the next release too.

Thank you very much again 😄

**Comment by wanhose** [comment]
@M1Aston both issues solved with 5.2.1 release, please update ✅

**Comment by M1Aston** [comment]
That was quick. I have just updated and everything is working fine now. Thanks very much.

**Comment by wanhose** [comment]
@happysurf, @M1Aston and anyone that is reading this message... from 5.3.0 you will be able to report site easily!

![image](https://user-images.githubusercontent.com/50265843/140499426-c3a1ab34-e900-42ba-9633-4d46716e08bf.png)

This button will notify me with the URL you're in and extension doesn't work well 🚀

What are you waiting for to update?

**Comment by wanhose** [comment]
@happysurf, @M1Aston and anyone that is reading this message... from 5.3.0 you will be able to report sites easily!

![image](https://user-images.githubusercontent.com/50265843/140499426-c3a1ab34-e900-42ba-9633-4d46716e08bf.png)

This button will notify me with the URL you're in and extension doesn't work well 🚀

What are you waiting for to update?
