### ISSUE TITLE
github.com

### ISSUE THREAD

**Issue by Rusenche** [wanhose/cookie-dialog-monster#243]
## Specifications
* Reason: Very slow loading of github.com
* URL: https://github.com/MasterKia/PersianBlocker/issues/40/
* User-Agent: Chromium v.114.0.5735.110

Very slow loading of https://github.com/MasterKia/PersianBlocker/issues/40/

_Cookie dialog monster v.6.3.2_, when enabled, extremely slows down the loading of this particular page until the last comment: https://github.com/MasterKia/PersianBlocker/issues/40/

If the _Cookie dialog monster v.6.3.2_ extension is turned off, then https://github.com/MasterKia/PersianBlocker/issues/40/ loads faster.

**Comment by wanhose** [comment]
Hi @Rusenche,

Thank you for the feedback. I'm working to solve this issue, can you kindly disable the extension here for a while?

The patch will be uploaded soon in the next 6.3.3 version. I've opened a PR to fix this so you can easily track this issue. I'll need a few days to test it carefully.

Thanks for your understanding. Have a nice day!

**Comment by Rusenche** [comment]
Supplement:

When the "_Contribute to this project_" extension is clicked - then it takes us to: https://**_www_**.github.com/wanhose/cookie-dialog-monster

You need to remove the **_www_** redirect.

The actual address is: https://github.com/wanhose/cookie-dialog-monster

**Comment by wanhose** [comment]
Doesn't it redirect you to this project then? I'm clicking it and getting the same result as the URL without **www**.

**Comment by Rusenche** [comment]
It redirects me, but you need to change it to transfer us to the correct address - without www in front, because now it first transfers us to www and then automatically the site removes it. I meant in the extension itself to change it to remove the www in front. ;)

**One more addition (not to create a new topic):**
On the site https://www.seir-sanduk.com/ - the video is not displayed. I show with a photo - see what is circled in red: https://postimg.cc/DmxY4kCv

Even if the extension is turned off for the site itself - https://www.seir-sanduk.com/ - it does not help.

To view this clip - the only solution is to disable the extension completely from here: chrome://extensions/?id=djcbfpkdhdkaflcigibkbpboflaplabg

**Comment by Rusenche** [comment]
I confirm that with version 6.3.**3** this site - https://github.com/MasterKia/PersianBlocker/issues/40 loads normally.

The redundant _www_ redirect is also left when we hit "_Contribute to this project_".


But there is still a problem with the site: https://www.seir-sanduk.com/ which issue I mentioned here: https://github.com/wanhose/cookie-dialog-monster/issues/243#issuecomment-1586240637

**Comment by wanhose** [comment]
Hi,

6.3.4 will be released in Chrome Web Store during today or tomorrow, (a bit longer for Edge users because the deploys there takes like 1 week).

Please tell me what you find @Rusenche. Thanks in advance!

**Comment by Rusenche** [comment]
@wanhose
I apologize for the late reply.

I confirm that with the new version 6.3.**4** the clip on https://www.seir-sanduk.com/ is rendered.

Just to add that in a few weeks https://www.seir-sanduk.com/ there are mirror sites and instead of this site it redirects to another and it is possible that the video is not displayed on the mirror site either. I reserve the right to write and you again make a correction and therefore. ;)

Well done.

**Comment by wanhose** [comment]
Of course, feel free to reopen this when you want. Happy to see that old bug fixed.

Thanks again for your feedback, have a good weekend! 😄

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Chrome (128.0.0.0)
#### 📝 Reason
Popup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed upPopup showed up
#### 🔗 URL
https://github.com/wanhose/cookie-dialog-monster/issues/842?hola=test
#### 🏷️ Version
7.2.0
