### ISSUE TITLE
tweakers.net

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#262]
## Specifications
- <b>Reason:</b> Popup showed up
- <b>URL:</b> https://tweakers.net/merk/2505/asustor/forum/
- <b>User-Agent:</b> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.79
- <b>Version:</b> 6.3.4

**Comment by M1Aston** [comment]
This website doesn't work properly while the extension is enabled.
There is a grey bar somewhere on the page (middle) that should be at the bottom.

![tweakers](https://github.com/wanhose/cookie-dialog-monster/assets/43113612/fa4a2abd-837c-454c-8b5a-e77fcb8810bc)

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Firefox (130.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://tweakers.net/
#### 🏷️ Version
7.2.2

**Comment by wanhose** [comment]
Uploaded some logic to handle this case in the new version `7.2.3`. Hopefully, it will fix many cases like this.
