### ISSUE TITLE
www.elmaz.com - causing the problem - lag

### ISSUE THREAD

**Issue by Rusenche** [wanhose/cookie-dialog-monster#284]
Hello again

After a lot of testing I found which extension was causing the problem - lag.

To reproduce the problem:
1. Log in to www.elmaz.com with an account (I'm not sure if it's possible without an account).
2. Install https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko/
3. Save for example 20 users - I mean save the session with 20 users open (it can be the same user - at that, opened 20 identical times) from www.elmaz.com in **Session buddy**.
4. Start the saved session from **Session buddy** to open a new window to load all 20 tabs simultaneously.
5. They load slowly.
6. Now close these 20 tabs.
7. _Turn off_ **Cookie dialog monster** only for www.elmaz.com.
8. _Start_ the saved session **Session buddy** to open a new window to load the 20 tabs simultaneously. **You will feel how much faster those open 20 tabs load**.

I tested with 60 and with 110 saved tabs in **Session buddy** and if the **Cookie dialog monster** on www.elmaz.com _is not turned off_ - **it all loads terribly slowly**. When the **Cookie dialog monster** is _turned off_ only for www.elmaz.com - **these hundred tabs load very quickly**.

@wanhose I hope you fix this problem. But it would be more than good if the extension also offered you to **export/import its settings**. If a user unintentionally uninstalls _Cookie dialog monster_ - all his individual settings on any sites disappear and cannot be restored.

**Comment by wanhose** [comment]
Hi @Rusenche,

Thanks for the information, the steps to reproduce the issue and also the suggestions about importing/exporting your settings. I'm working on this. I'll keep you posted.

**Comment by Rusenche** [comment]
> Hi @Rusenche,
> 
> Thanks for the information, the steps to reproduce the issue and also the suggestions about importing/exporting your settings. I'm working on this. I'll keep you posted.

@wanhose, I can provide the saved settings to **Session buddy** with _109_ tabs set.

My point is that by running this saved session (in **Session buddy**) - you will be able to observe quite accurately the significant delay that occurs with the **Cookie dialog monster** enabled. If you want - I can provide this file?!

**Comment by wanhose** [comment]
> 

Yes, please. It'll be helpful.

**Comment by Rusenche** [comment]
>@wanhose: Yes, please. It'll be helpful.


I have uploaded the required file.

Test with Cookie dialog monster on and `Cookie dialog monster` off to reproduce the noticeable difference.

Besides settings import/export options, the extension needs a visible option - on which site what setting is set. At the moment we have to remember which site the advanced is turned off on, which is not practical.

[session_buddy_export_2023_09_12_15_15_15.txt](https://github.com/wanhose/cookie-dialog-monster/files/12586278/session_buddy_export_2023_09_12_15_15_15.txt)

**Comment by Rusenche** [comment]
I can't comment if the new version 6.4.0 fixes the issue from this thread and the other thread https://github.com/wanhose/cookie-dialog-monster/issues/287 because on [https://chrome.google. com/webstore/detail/cookie-dialog-monster/djcbfpkdhdkaflcigibkbpboflaplabg/](https://chrome.google.com/webstore/detail/cookie-dialog-monster/djcbfpkdhdkaflcigibkbpboflaplabg/) the new version 6.4.0 is gone. Although it's been 5 days since you posted on github.com that there is a new version 6.4.0.

**Comment by wanhose** [comment]
Yes @Rusenche, you are right. The review is taking longer than expected by the Chrome Web Store team. That's the reason I didn't comment in your issues yet. I'll keep you posted, sorry for the inconveniences.

**Comment by Rusenche** [comment]
@wanhose, I confirm that version 6.4.0 fixes the problem mentioned in this thread.

Well done for the great work. :}
