### ISSUE TITLE
https://translate.google.com/ - causing the problem - lag

### ISSUE THREAD

**Issue by Rusenche** [wanhose/cookie-dialog-monster#287]
Hello again

After a lot of testing I found which extension was causing the problem – lag.

To reproduce the problem:
- start writing a long text in https://translate.google.com/ and a long wait begins... and/or paste here this address – again for testing, because I had to write it now, communicating with a developer:
- [https://translate.google.com/?sl=auto&tl=en&text=%D0%9D%D0%B0%D0%BD%D0%B5%D1%81%D0%BE%D1%85%20%D0 %BF%D1%80%D0%B5%D0%B4%D0%B8%20%D1%82%D0%BE%D0%B2%D0%B0%205%20%D0%BC%D0%B0%D0 %BB%D0%BA%D0%B8%20%D0%BA%D0%BE%D1%80%D0%B5%D0%BA%D1%86%D0%B8%D0%B8.%0A%0A% D0%9F%D1%80%D0%BE%D0%BC%D0%B5%D0%BD%D0%B8%D1%85%20%D1%82%D0%BE%D0%B2%D0%B0% 20%D0%BC%D0%B5%D0%BD%D1%8E%20%D0%B5%D1%82%D0%BE%20%D1%82%D0%B0%D0%BA%D0%B0% 3A%0A%5BMain%20menu%2FMovie%5D%0A01%3DOpen%20movie%0A02%3DClose%20movie%0A03%3DInformation%0A04%3DVideo%20preview%20mode%0A05%3DShow%20subtitles%0A06%3DSave%20media%20startup% 20file%0A07%3DAudio%20stream%0A08%3DNone%0A09%3DVideo%20renderer%0A10%3DDefault%0A11%3DVMR9%0A12%3DVLC%0A%0A%D0%9D%D0%BE%20%D1%81%D0% B5%20%D1%80%D0%B0%D0%B7%D0%B1%D1%80%D0%B0%D1%85%D0%BC%D0%B5%2C%20%D1%87%D0% B5%20%D0%B2%20%D1%81%D0%BB%D0%B5%D0%B4%D0%B2%D0%B0%D1%89%D0%B0%D1%82%D0%B0% 20%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F%20%D0%BC%D0%B5%D0%BD%D1%8E%D1%82%D0% BE%20%D1%89%D0%B5%20%D0%B8%D0%B7%D0%B3%D0%BB%D0%B5%D0%B6%D0%B4%D0%B0%20%D0% B5%D1%82%D0%BE%20%D1%82%D0%B0%D0%BA%D0%B0%3A%0A%0A%5BVideo%20popup%20menu%5D%0A01%3DEnter%20full%20screen% 0A02%3DZoom%20to%20%25d%25%25%0A03%3DReset%20subtitle%20vertical%20position%0A04%3DAspect%20ratio%0A05%3DOriginal%0A06%3DExit%20full%20screen%0A%0A%D0%A1% D1%8A%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BD%D0%BE%20%D0%BF%D1%80%D0%BE%D0%BC% D0%B5%D0%BD%D0%B8%D1%85%20%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA% D0%B8%D1%8F%20%D0%B5%D0%B7%D0%B8%D0%BA%D0%BE%D0%B2%20%D1%84%D0%B0%D0%B9%D0% BB%20%D0%B4%D0%B0%20%D0%B5%20%D0%BF%D0%BE%20%D1%82%D0%BE%D0%B7%D0%B8%20%D0% BD%D0%B0%D1%87%D0%B8%D0%BD.%0A%0A%D0%A9%D0%B5%20%D0%BF%D1%80%D0%BE%D0%BC%D0 %B5%D0%BD%D1%8F%20%D0%B8%20%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA %D0%B8%D1%8F%D1%82%20%D0%B5%D0%B7%D0%B8%D0%BA%D0%BE%D0%B2%20%D1%84%D0%B0%D0 %B9%D0%BB%20%D0%B4%D0%B0%20%D1%81%D1%8A%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81 %D1%82%D0%B2%D0%B0%20%D0%BD%D0%B0%20%D0%BF%D1%80%D0%BE%D0%BC%D1%8F%D0%BD%D0 %B0%D1%82%D0%B0%20(%D0%B8%D0%BC%D0%B0%D0%BC%20%D0%BF%D1%80%D0%B5%D0%B4%D0% B2%D0%B8%D0%B4%20%D0%B7%D0%B0%20%2206%3DExit%20full%20screen%22.%20%D0%A0%D0%B5%D1%88%D0%B8 %D1%85%D0%BC%D0%B5%2C%20%D1%87%D0%B5%20%D1%89%D0%B5%20%D0%B5%20%D0%BD%D0%B0 %D0%B9-%D0%B4%D0%BE%D0%BB%D1%83%20%D0%B2%20%D0%BC%D0%B5%D0%BD%D1%8E%D1%82% D0%BE%20%D0%B7%D0%B0%20%D1%83%D0%BB%D0%B5%D1%81%D0%BD%D0%B5%D0%BD%D0%B8%D0% B5).%0A%0A%D0%98%D0%BC%D0%B0%D0%BC%20%D0%B2%D1%8A%D0%BF%D1%80%D0%BE%D1%81. %20%D0%92%20%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D1%8F%20 %D0%B5%D0%B7%D0%B8%D0%BA%D0%BE%D0%B2%20%D1%84%D0%B0%D0%B9%D0%BB%20%D0%B8%D0 %BC%D0%B0%20%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%BD%D0%B8%D0%B5%20 %D0%BD%D0%B0%3A%0A%5BMain%20menu%2FTools%5D%0A05%3DInformation%20and%20errors%0A06%3DInformation%20and%20errors...%0A%0A%D0%93%D1% 80%D0%B5%D1%88%D0%BD%D0%BE%20%D0%BB%D0%B8%20%D0%B5%20%D1%82%D0%BE%D0%B2%D0% B0%3F!%3F!&op=translate](https://translate.google.com/?sl=auto&tl=en&text=%D0%9D%D0%B0%D0%BD%D0%B5%D1%81%D0%BE%D1%85%20%D0%BF%D1%80%D0%B5%D0%B4%D0%B8%20%D1%82%D0%BE%D0%B2%D0%B0%205%20%D0%BC%D0%B0%D0%BB%D0%BA%D0%B8%20%D0%BA%D0%BE%D1%80%D0%B5%D0%BA%D1%86%D0%B8%D0%B8.%0A%0A%D0%9F%D1%80%D0%BE%D0%BC%D0%B5%D0%BD%D0%B8%D1%85%20%D1%82%D0%BE%D0%B2%D0%B0%20%D0%BC%D0%B5%D0%BD%D1%8E%20%D0%B5%D1%82%D0%BE%20%D1%82%D0%B0%D0%BA%D0%B0%3A%0A%5BMain%20menu%2FMovie%5D%0A01%3DOpen%20movie%0A02%3DClose%20movie%0A03%3DInformation%0A04%3DVideo%20preview%20mode%0A05%3DShow%20subtitles%0A06%3DSave%20media%20startup%20file%0A07%3DAudio%20stream%0A08%3DNone%0A09%3DVideo%20renderer%0A10%3DDefault%0A11%3DVMR9%0A12%3DVLC%0A%0A%D0%9D%D0%BE%20%D1%81%D0%B5%20%D1%80%D0%B0%D0%B7%D0%B1%D1%80%D0%B0%D1%85%D0%BC%D0%B5%2C%20%D1%87%D0%B5%20%D0%B2%20%D1%81%D0%BB%D0%B5%D0%B4%D0%B2%D0%B0%D1%89%D0%B0%D1%82%D0%B0%20%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F%20%D0%BC%D0%B5%D0%BD%D1%8E%D1%82%D0%BE%20%D1%89%D0%B5%20%D0%B8%D0%B7%D0%B3%D0%BB%D0%B5%D0%B6%D0%B4%D0%B0%20%D0%B5%D1%82%D0%BE%20%D1%82%D0%B0%D0%BA%D0%B0%3A%0A%0A%5BVideo%20popup%20menu%5D%0A01%3DEnter%20full%20screen%0A02%3DZoom%20to%20%25d%25%25%0A03%3DReset%20subtitle%20vertical%20position%0A04%3DAspect%20ratio%0A05%3DOriginal%0A06%3DExit%20full%20screen%0A%0A%D0%A1%D1%8A%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D0%BD%D0%BE%20%D0%BF%D1%80%D0%BE%D0%BC%D0%B5%D0%BD%D0%B8%D1%85%20%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D1%8F%20%D0%B5%D0%B7%D0%B8%D0%BA%D0%BE%D0%B2%20%D1%84%D0%B0%D0%B9%D0%BB%20%D0%B4%D0%B0%20%D0%B5%20%D0%BF%D0%BE%20%D1%82%D0%BE%D0%B7%D0%B8%20%D0%BD%D0%B0%D1%87%D0%B8%D0%BD.%0A%0A%D0%A9%D0%B5%20%D0%BF%D1%80%D0%BE%D0%BC%D0%B5%D0%BD%D1%8F%20%D0%B8%20%D0%B1%D1%8A%D0%BB%D0%B3%D0%B0%D1%80%D1%81%D0%BA%D0%B8%D1%8F%D1%82%20%D0%B5%D0%B7%D0%B8%D0%BA%D0%BE%D0%B2%20%D1%84%D0%B0%D0%B9%D0%BB%20%D0%B4%D0%B0%20%D1%81%D1%8A%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B0%20%D0%BD%D0%B0%20%D0%BF%D1%80%D0%BE%D0%BC%D1%8F%D0%BD%D0%B0%D1%82%D0%B0%20(%D0%B8%D0%BC%D0%B0%D0%BC%20%D0%BF%D1%80%D0%B5%D0%B4%D0%B2%D0%B8%D0%B4%20%D0%B7%D0%B0%20%2206%3DExit%20full%20screen%22.%20%D0%A0%D0%B5%D1%88%D0%B8%D1%85%D0%BC%D0%B5%2C%20%D1%87%D0%B5%20%D1%89%D0%B5%20%D0%B5%20%D0%BD%D0%B0%D0%B9-%D0%B4%D0%BE%D0%BB%D1%83%20%D0%B2%20%D0%BC%D0%B5%D0%BD%D1%8E%D1%82%D0%BE%20%D0%B7%D0%B0%20%D1%83%D0%BB%D0%B5%D1%81%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5).%0A%0A%D0%98%D0%BC%D0%B0%D0%BC%20%D0%B2%D1%8A%D0%BF%D1%80%D0%BE%D1%81.%20%D0%92%20%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D1%8F%20%D0%B5%D0%B7%D0%B8%D0%BA%D0%BE%D0%B2%20%D1%84%D0%B0%D0%B9%D0%BB%20%D0%B8%D0%BC%D0%B0%20%D0%BF%D0%BE%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%BD%D0%B8%D0%B5%20%D0%BD%D0%B0%3A%0A%5BMain%20menu%2FTools%5D%0A05%3DInformation%20and%20errors%0A06%3DInformation%20and%20errors...%0A%0A%D0%93%D1%80%D0%B5%D1%88%D0%BD%D0%BE%20%D0%BB%D0%B8%20%D0%B5%20%D1%82%D0%BE%D0%B2%D0%B0%3F!%3F!&op=translate)

If you turn off the extension **Cookie dialog monster** for https://translate.google.com/ – the delay is not felt.

@wanhose I hope you fix this problem. There is indeed a problem with https://translate.google.com/ – the delay is felt.

**Comment by wanhose** [comment]
Hi @Rusenche,

Thanks for the issue, you are right so I'm going to take a look. I'll keep you posted.

**Comment by Rusenche** [comment]
@wanhose, version 6.4.0 regarding the problem described in this thread with https://translate.google.com/ ... how can I put it - a new problem has appeared.

When we open in the browser https://translate.google.com/ - the extension is inactive. I mean we can neither enable the extension nor can we disable the extension specifically for https://translate.google.com/. The extension icon is matte/dark and cannot be activated. By the look of the extension icon - it looks like it's turned off, but it can't be turned on in any way.

For greater clarity - in [chrome-extension://djcbfpkdhdkaflcigibkbpboflaplabg/options.html] I have removed https://translate.google.com/ which address I had added in the previous version - as an exception for this site so that it can https://translate.google.com/ is used. But now with the new version the extension is inactive and cannot be turned on.

So I can't comment on the new version - it's not clear if it fixes the problem described in this thread because a new problem has been introduced with the new version.

I'm also attaching a picture so you can see that even the menu doesn't appear.

For clarification - I took the menu from the site elmaz.com and that is why elmaz.com is visible in the picture. There is no way for me to capture and display a photo for https://translate.google.com/ because such a menu does not appear.

![translate](https://github.com/wanhose/cookie-dialog-monster/assets/18578128/a310defc-d79e-4bfb-8dd9-0cb7b3567f19)

![transl](https://github.com/wanhose/cookie-dialog-monster/assets/18578128/5512c014-9f4a-4a7f-b400-3619d30c753b)

**Comment by Rusenche** [comment]
@wanhose,@wanhose, there are two points.

I've tested my proposed one and a new list import/export option has already been added.

1. When exporting to a list - the extension suggests the name be "1696670624306". I suggest making it date.month.year - like this: 07.10.2023.
2. If you add a random exception address and decide to delete it - the address remains there. This is misleading because you have to manually press F5 (refresh) on the keyboard to make the deleted address disappear.

@wanhose please note these 2 points and fix them because the development so far is perfect. :}

**Comment by wanhose** [comment]
> @wanhose, version 6.4.0 regarding the problem described in this thread with https://translate.google.com/ ... how can I put it - a new problem has appeared.
> 
> When we open in the browser https://translate.google.com/ - the extension is inactive. I mean we can neither enable the extension nor can we disable the extension specifically for https://translate.google.com/. The extension icon is matte/dark and cannot be activated. By the look of the extension icon - it looks like it's turned off, but it can't be turned on in any way.
> 
> For greater clarity - in chrome-extension://djcbfpkdhdkaflcigibkbpboflaplabg/options.html I have removed https://translate.google.com/ which address I had added in the previous version - as an exception for this site so that it can https://translate.google.com/ is used. But now with the new version the extension is inactive and cannot be turned on.
> 
> So I can't comment on the new version - it's not clear if it fixes the problem described in this thread because a new problem has been introduced with the new version.
> 
> I'm also attaching a picture so you can see that even the menu doesn't appear.
> 
> For clarification - I took the menu from the site elmaz.com and that is why elmaz.com is visible in the picture. There is no way for me to capture and display a photo for https://translate.google.com/ because such a menu does not appear.
> 
> ![translate](https://user-images.githubusercontent.com/18578128/273375664-a310defc-d79e-4bfb-8dd9-0cb7b3567f19.png)
> 
> ![transl](https://user-images.githubusercontent.com/18578128/273375866-5512c014-9f4a-4a7f-b400-3619d30c753b.png)

Hi @Rusenche,

You are right, I've totally disabled the extension in `https://google.translate.com` page. It is a very expensive page due its continuous rerenders when you are typing and many other things related to hidden iframes which run the extension anyway (as intended).

So after a bit of research, I've decided to turn off the extension in this page definitely. Why? Because this page doesn't have a cookie dialog already. It redirects you to `https://consent.google.com` to set your preferences which is a different page.

I'm working on auto-decline this last page. So don't worry about this, there are a few pages that are disabled by me. You can see them in the `exclude_matches` section of the `manifest.json` file of this project.

Hope this explanation works for you. Thanks for the feedback again.

**Comment by wanhose** [comment]
> @wanhose, there are two points.
> 
> I've tested my proposed one and a new list import/export option has already been added.
> 
> 1. When exporting to a list - the extension suggests the name be "1696670624306". I suggest making it date.month.year - like this: 07.10.2023.
> 2. If you add a random exception address and decide to delete it - the address remains there. This is misleading because you have to manually press F5 (refresh) on the keyboard to make the deleted address disappear.
> 
> @wanhose please note these 2 points and fix them because the development so far is perfect. :}

Thanks for your suggestions. Working on them.

**Comment by Rusenche** [comment]
> Hi @Rusenche,
> 
> You are right, I've totally disabled the extension in `https://google.translate.com` page. It is a very expensive page due its continuous rerenders when you are typing and many other things related to hidden iframes which run the extension anyway (as intended).
> 
> So after a bit of research, I've decided to turn off the extension in this page definitely. Why? Because this page doesn't have a cookie dialog already. It redirects you to `https://consent.google.com` to set your preferences which is a different page.
> 
> I'm working on auto-decline this last page. So don't worry about this, there are a few pages that are disabled by me. You can see them in the `exclude_matches` section of the `manifest.json` file of this project.
> 
> Hope this explanation works for you. Thanks for the feedback again.

Hi @wanhose

For myself, while writing my comment about the disabled extension observation for https://translate.google.com/ I suspected that this was a deliberate effect/result, but I wanted to discuss this site specifically. Maybe for more clarity - it's better to add the changes when publishing new versions so this information is there, because I also suspected you did it intentionally, but it wasn't in the changelist. ;))

**Comment by wanhose** [comment]
Added this information to the new release and also to the old ones. You can check this out in the releases page.

**Comment by wanhose** [comment]
> > Hi @Rusenche,
> > You are right, I've totally disabled the extension in `https://google.translate.com` page. It is a very expensive page due its continuous rerenders when you are typing and many other things related to hidden iframes which run the extension anyway (as intended).
> > So after a bit of research, I've decided to turn off the extension in this page definitely. Why? Because this page doesn't have a cookie dialog already. It redirects you to `https://consent.google.com` to set your preferences which is a different page.
> > I'm working on auto-decline this last page. So don't worry about this, there are a few pages that are disabled by me. You can see them in the `exclude_matches` section of the `manifest.json` file of this project.
> > Hope this explanation works for you. Thanks for the feedback again.
> 
> Hi @wanhose
> 
> For myself, while writing my comment about the disabled extension observation for https://translate.google.com/ I suspected that this was a deliberate effect/result, but I wanted to discuss this site specifically. Maybe for more clarity - it's better to add the changes when publishing new versions so this information is there, because I also suspected you did it intentionally, but it wasn't in the changelist. ;))

Added this information to the new release and also to the old ones. You can check this out in the releases page.

**Comment by Rusenche** [comment]
Hi @wanhose 


Yes, for version 6.4.0 you are right that it says it, but the update via https://chrome.google.com/webstore/detail/cookie-dialog-monster/djcbfpkdhdkaflcigibkbpboflaplabg/ came ... 7 days later as a delay from google . I received the 6.4.0 update today and I see now that you have listed the changes I am writing about.

And I see that 8 hours ago you published a new version 6.4.1, which maybe in 7 days will appear as an update on https://chrome.google.com/webstore/detail/cookie-dialog-monster/djcbfpkdhdkaflcigibkbpboflaplabg/.

@wanhose, in the new version, among the changes, I don't see that this is what I call problematic - when you added some exception address - and you decide to delete it, the address remains there. Unless F5 is pressed on the keyboard. Is this "effect" resolved in version 6.4.1?

**Comment by wanhose** [comment]
> Hi @wanhose
> 
> Yes, for version 6.4.0 you are right that it says it, but the update via https://chrome.google.com/webstore/detail/cookie-dialog-monster/djcbfpkdhdkaflcigibkbpboflaplabg/ came ... 7 days later as a delay from google . I received the 6.4.0 update today and I see now that you have listed the changes I am writing about.
> 
> And I see that 8 hours ago you published a new version 6.4.1, which maybe in 7 days will appear as an update on https://chrome.google.com/webstore/detail/cookie-dialog-monster/djcbfpkdhdkaflcigibkbpboflaplabg/.
> 
> @wanhose, in the new version, among the changes, I don't see that this is what I call problematic - when you added some exception address - and you decide to delete it, the address remains there. Unless F5 is pressed on the keyboard. Is this "effect" resolved in version 6.4.1?

Hi @Rusenche,

The issue about items still appearing before you refresh the page is fixed now in the version 6.4.1. Let's wait to the Google team to publish this version.

**Comment by Rusenche** [comment]
Hi @wanhose

I already have the extension updated to version 6.4.**1**.

The exception deletion issue I mentioned has now been resolved.

Well done for the quick intervention and for the published new version. Thanks also for taking the time out of your spare time to develop this wonderful extension.

But I noticed a new problem. Somehow, the extension does not correctly count the current day, because when exporting it counts and offers as a name - day 01, and we are the ninth day (of the month). Even the month is wrong, because it is presented as 09, and we are in the 10th month.

Here is what is suggested for the settings export name: "`20230901`".

@wanhose, can you really reverse - I mean have a name suggested with "`date.month.year`" rather than as it is now - with year first?

As an example, I give the Violentmonkey extension. In its settings, a name option can be set on export, and I set it like this: `[Violentmonkey] - DD.MM.YYYY - HH.mm.ss`. Accordingly, the suggested export name includes seconds and looks like this: `Violentmonkey - 09.10.2023 - 16.05.50`.

**Comment by wanhose** [comment]
> Hi @wanhose
> 
> I already have the extension updated to version 6.4.**1**.
> 
> The exception deletion issue I mentioned has now been resolved.
> 
> Well done for the quick intervention and for the published new version. Thanks also for taking the time out of your spare time to develop this wonderful extension.
> 
> But I noticed a new problem. Somehow, the extension does not correctly count the current day, because when exporting it counts and offers as a name - day 01, and we are the ninth day (of the month). Even the month is wrong, because it is presented as 09, and we are in the 10th month.
> 
> Here is what is suggested for the settings export name: "`20230901`".
> 
> @wanhose, can you really reverse - I mean have a name suggested with "`date.month.year`" rather than as it is now - with year first?
> 
> As an example, I give the Violentmonkey extension. In its settings, a name option can be set on export, and I set it like this: `[Violentmonkey] - DD.MM.YYYY - HH.mm.ss`. Accordingly, the suggested export name includes seconds and looks like this: `Violentmonkey - 09.10.2023 - 16.05.50`.

Hi @Rusenche,

I've decided to use a more standard format for the date (like ISO 8601) without dashes. In the next update I'll include an option to set the name you want before you export the file.

For now, I recommend you to rename it manually. Sorry for the inconveniences.

**Comment by Rusenche** [comment]
Hi @wanhose

I thought of one more thing. Since addresses can be deleted in the extension settings - why not add an option to manually add addresses - I mean here chrome-extension://djcbfpkdhdkaflcigibkbpboflaplabg/options.html?

**Comment by Rusenche** [comment]
> Hi @wanhose
> 
> I thought of one more thing. Since addresses can be deleted in the extension settings - why not add an option to manually add addresses - I mean here chrome-extension://djcbfpkdhdkaflcigibkbpboflaplabg/options.html?

@wanhose

**Comment by wanhose** [comment]
> > Hi @wanhose
> > I thought of one more thing. Since addresses can be deleted in the extension settings - why not add an option to manually add addresses - I mean here chrome-extension://djcbfpkdhdkaflcigibkbpboflaplabg/options.html?
> 
> @wanhose

Hi @Rusenche,

Thanks for the reminder. I totally forgot this. I've uploaded a new update right now that includes this.

**Comment by wanhose** [comment]
Closing this due inactivity @Rusenche.
