### ISSUE TITLE
Report site option

### ISSUE THREAD

**Issue by M1Aston** [wanhose/cookie-dialog-monster#31]
Can the report site option also be used for websites where CDM causes problems (when blocking cookies) or should it simply be disabled for those site?

**Comment by wanhose** [comment]
Hey @M1Aston!

Could you clarify the reason of your issue? You can use the report site option to report sites where CDM doesn't work well or doesn't work completely.

**Comment by M1Aston** [comment]
Well, sometimes it breaks stuff. :-D 
Meaning, some websites won't load or function properly when enabled. Can these issues be reported by using the Report site right click option or is that just meant to be used for reporting when cookie messages pop up?

**Comment by wanhose** [comment]
Yes, they can, this is the behaviour of this button because it will notify me with your current page 😁
