### ISSUE TITLE
Footer in the wrong place

### ISSUE THREAD

**Issue by Albusoline** [wanhose/cookie-dialog-monster#37]
Hi.
Using MantisBT, the footer was at the bottom of the active window (and not at the bottom of the page). However, when scrolling to the end of the page, it stayed where it was on the page and was covering elements of the website. When I scrolled the page, the footer was moving up accordingly.

After deactivating cookie-dialog-monster, the footer was back where it belongs.

Using linux and Firefox 97 as well as Windows with firefox 97, Cookie dialog Monster v 5.4.6

**Comment by wanhose** [comment]
Welcome to the repository @Albusoline!

Thank you a lot for your feedback. I saw this problem in many pages because they are absolute positioning the footer and the extension changes this behaviour.

Could you write us here a list of URLs where it happens? We'll fix it as soon as you send it.

**Comment by wanhose** [comment]
Hi @Albusoline,

Sorry for this too late answer. I was working in a deep refactor to this project merging both projects we have right now (the browser extension and the report service), I didn't have time to solve this issue till now but I'm currently working in the next version that will solve this issue.

**Comment by wanhose** [comment]
[5.5.0](https://github.com/wanhose/cookie-dialog-monster/releases/tag/5.5.0) is out @Albusoline!

Now we are able to add exceptions in certain pages to avoid the problem you said. As I think this issue is solved, I'm going to close this but please feel free to reopen the discussion if the problem persists.
