### ISSUE TITLE
alliedtelesis.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#453]
## Specifications
- <b>Reason:</b> Popup showed up
- <b>URL:</b> https://www.alliedtelesis.com/fr/fr/documents/visio-stencil-ifs802sp-80-and-poe-80
- <b>User-Agent:</b> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
- <b>Version:</b> 6.4.6

**Comment by wanhose** [comment]
Please, update your extension and then try again. If the problem persists, feel free to reopen this issue.

**Comment by devilcraef** [comment]
On Firefox, i'm on this version (the last available) :
![image](https://github.com/wanhose/cookie-dialog-monster/assets/39867753/e66ebb93-ab81-4918-8f9b-bfbae0576c01)

**Comment by wanhose** [comment]
Welcome @devilcraef,

Thanks for adding extra information about this issue. This issue was originally sent from a different version than **5.5.5**.

Due to technical issues with the Firefox Team, our extension's support on Mozilla Add-ons has ended with version **5.5.5**. However, you can still run a development copy of the last version of the extension. You can follow [this guide](https://github.com/wanhose/cookie-dialog-monster/tree/main/packages/browser-extension#installation-only-for-developers-or-mozilla-firefox-users) to install the latest version in your browser.

If you have problems installing the extension, please send me an email to [hello@wanhose.dev](mailto:hello@wanhose.dev) and I can help you to install the latest version in a different way.

**Comment by wanhose** [comment]
Closing this issue due inactivity. Feel free to reopen this issue if needed.
