### ISSUE TITLE
solarwinds.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#481]
## Specifications
- <b>Reason:</b> Cannot click
- <b>URL:</b> https://www.solarwinds.com/free-tools/solar-putty
- <b>User-Agent:</b> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
- <b>Version:</b> 7.0.2

**Comment by devilcraef** [comment]
Hi wanhose, actually it's not the click which doesn't work, it's the scroll (with the mouse wheel). I don't have this choice in the window so i picked up the nearest

**Comment by wanhose** [comment]
Hi @devilcraef,

Thanks for reporting this issue. I've just uploaded a fix, you don't need to wait for an extension update. It was an update in the database so, it will be fixed as soon as the cache expires (that means in your next browser fully reload or computer reboot).

Please, drop here a message if the issue was fixed :smile:

**Comment by wanhose** [comment]
Closing this issue due inactivity. Feel free to reopen this issue if needed.
