### ISSUE TITLE
perplexity.ai

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#487]
## Specifications
- <b>Reason:</b> Popup showed up
- <b>URL:</b> https://www.perplexity.ai/
- <b>User-Agent:</b> Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
- <b>Version:</b> 7.0.2

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://www.perplexity.ai/
#### 🏷️ Version
7.3.0

**Comment by sonnyxq** [comment]
![Screenshot 2024-09-20 213048](https://github.com/user-attachments/assets/94d7e0b9-cc0b-4155-bfdb-908d45bcc07e)

**Comment by wanhose** [comment]
> ![Screenshot 2024-09-20 213048](https://private-user-images.githubusercontent.com/60904977/369533230-94d7e0b9-cc0b-4155-bfdb-908d45bcc07e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjgyMTUsIm5iZiI6MTcyODIyNzkxNSwicGF0aCI6Ii82MDkwNDk3Ny8zNjk1MzMyMzAtOTRkN2UwYjktY2MwYi00MTU1LWJmZGItOTA4ZDQ1YmNjMDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE1MTgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYjM3OGU2M2FmZTFkMjMwZjE2NWRjMjUyNWY5ZWNlMTMwYjJhMmRkOTFjNjEwYTAyODkwMmZkZWI5OGRlMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7V7BXnnlbpsC8yvpSqLXhF4c4sE88U2uOq5_hLImf2U)

Hi @sonnyxq,

Please, upgrade to latest extension version `7.3.2`. It doesn't show up for me anymore.

Sorry for the inconveniences.
