### ISSUE TITLE
Report site on right click is missing

### ISSUE THREAD

**Issue by mnn** [wanhose/cookie-dialog-monster#49]
I saw this option once, used it and now I cannot report more broken sites (e.g. https://www.typescriptlang.org/play). The option in right click menu is always missing (regardless if I have CDM enabled or not on current site). Or maybe I am doing something wrong?

extension version: 5.5.6
browser: Vivaldi 5.3.2679.68 (Linux)

<img width="321" alt="2022-07-25_19-07" src="https://user-images.githubusercontent.com/1975567/180835165-aef91b03-a4f3-4682-84a5-24d84bd67e4d.png">

**Comment by wanhose** [comment]
Welcome to the community @mnn,

Thanks for your feedback, just released [a new version](https://github.com/wanhose/cookie-dialog-monster/releases/tag/5.5.7) that fixes this problem. Hope it could be reviewed quickly by Google but it's on the way!

**Comment by wanhose** [comment]
This issue is going to be closed due inactivity. Please, feel free to reopen the issue if the problem persists. Thanks again for your feedback.
