### ISSUE TITLE
Extension effects are unclear

### ISSUE THREAD

**Issue by Cwpute** [wanhose/cookie-dialog-monster#57]
Hi, i'm looking for replacement for the I Don't Care About Cookies extension, and found about this one. I'd like to give it a try but it's rather unclear what this extension does exactly.

Does it only hides pop-ups asking for your consent ?
Does it accept all cookies by default ?
Does it reject all cookies by default ?
Does it sometimes accept, sometimes reject, sometimes hides consent pop-ups ?

**Comment by wanhose** [comment]
Hi @Cwpute,

Welcome to the community and thank you for your questions. The main purpose of this extension is to avoid dialogs visually what means just remove them from the page without accepting/declining something without your consent.

As always, there are exceptions like pages that contain dialogs we can't remove, in those cases we try to decline in first instance and if not possible (and in last case) we accept those cookies automatically.

If you are curious to see where we accept/decline and where we just remove, I suggest you to see these two files [elements](https://github.com/wanhose/cookie-dialog-monster/blob/main/data/elements.txt) where we just remove using CSS selectors and [fixes](https://github.com/wanhose/cookie-dialog-monster/blob/main/data/fixes.txt) where we accept or decline them using a different system specifying the page, the selector and the action we want to do.

Also I would like to say that pull requests are welcome, you can contribute through code or just surfing the Internet reporting sites where this extension doesn't work:

<img src="https://www.cookie-dialog-monster.com/images/report.png">

**Comment by Cwpute** [comment]
Hey, thanks for the answer. I'm a mostly incompetent user looking for answers unfortunately, not a knowable potential contributor. Good call asking though! that might bring you more people on board.

**Comment by wanhose** [comment]
Here contributors are as same valuable as users so don't worry!

Hope you can give a chance to the extension 🙂

**Comment by Cwpute** [comment]
(Oh i'd suggest being more precise about the way this extension works both on the website page and on this github descrition. I won't be the only one to wonder how it works i guess)

**Comment by wanhose** [comment]
Thank you @Cwpute, I forgot to mention that I'm working on this after your issue 😉

**Comment by wanhose** [comment]
Hi again @Cwpute,

I'm doing some updates to the documentation and also to the extension. Please take a look to [the new documentation](https://github.com/wanhose/cookie-dialog-monster/pull/304/commits/09f2ce9f22f030286812debef797a135e64e973c) and see if it provides enough information about what you were searching before.

Thanks again!
