### ISSUE TITLE
askubuntu.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#601]
#### Browser
Firefox (128.0)
#### Reason
Popup showed up
#### URL
https://askubuntu.com/questions/841847/mono-package-for-wine-is-not-installed/992215#992215
#### Version
7.0.4

**Comment by dreirund** [comment]
Screenshot:

---

![image](https://github.com/wanhose/cookie-dialog-monster/assets/1590519/4bdebbe2-925d-4f0b-9ed8-0507aa99cde0)

**Comment by wanhose** [comment]
> Screenshot:
> 
> ![image](https://private-user-images.githubusercontent.com/1590519/340334136-4bdebbe2-925d-4f0b-9ed8-0507aa99cde0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MzYwMTIsIm5iZiI6MTcxODYzNTcxMiwicGF0aCI6Ii8xNTkwNTE5LzM0MDMzNDEzNi00YmRlYmJlMi05MjVkLTRmMGItOWVkOC0wNTA3YWE5OWNkZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTdUMTQ0ODMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzQ2YjBkODA2NDhjYTg1MTU2ZTBmOWU0YjdlNDYwZDYyYzk2ZDVmMGIzOGU3ODM1MmYzYzczNDVkMTE0MjM1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vEAuq1GCh0MaWsnvaWAv6UR0yOCd-RqERAdIOjZtMnU)

Hey @dreirund,

Thanks for the feedback, have you restarted your browser after the installation or are you browsing in private mode? If you are browsing in private mode, remember to allow the extension to run in private.

<img width="758" alt="image" src="https://github.com/wanhose/cookie-dialog-monster/assets/50265843/f49e22e1-3481-4be3-845f-9713546cbbf0">

About the "restart" thing, each time you restart your browser, the extension will be removed. This is another of Firefox policies that, we (the developers) don't understand. In my opinion, I only recommend you to run this extension if you are using a Chromium-based browser.

If you are looking for privacy-focused browsers, an alternative could be Brave.

Sorry for the inconveniences, again 😅

**Comment by dreirund** [comment]
On Mon, 17 Jun 2024 08:55:46 -0700, wanhose ***@***.***>
wrote:

> Thanks for the feedback, have you restarted your browser after the
> installation or are you browsing in private mode?

Neither.

> About the "restart" thing, each time you restart your browser, the
> extension will be removed.
> This is another of Firefox policies that,
> we (the developers) don't understand.

I know that other addons are distributed as "proper" firefox addons
(`.xpi` file) directly from third-parties and not via
addons.mozilla.org.

So maybe you can pack it as a proper `.xpi` file even without the
ability to host at addons.mozilla.org?


> In my opinion, I only recommend
> you to run this extension if you are using a Chromium-based browser.

OK, so I need to switch back to some other addon ("I still don't care
about cookies"), which is not really maintained.

Regards!

**Comment by wanhose** [comment]
> I know that other addons are distributed as "proper" firefox addons (`.xpi` file) directly from third-parties and not via addons.mozilla.org. So maybe you can pack it as a proper `.xpi` file even without the ability to host at addons.mozilla.org?

I'm studying this option, but it will take time. Thanks anyway for trying to use our extension!
