### ISSUE TITLE
myprivacy.dpgmedia.nl

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#613]
#### Browser
Firefox (127.0)
#### Reason
Popup showed up
#### URL
https://myprivacy.dpgmedia.nl/consent?siteKey=Dl16ymCePojG0NiW&callbackUrl=https%3A%2F%2Fwww.destentor.nl%2Fprivacy-gate%2Faccept-tcf2%3FredirectUri%3D%252Fgezond%252Fpatienten-met-lage-inkomens-krijgen-minder-uitgebreide-behandeling-bij-kanker~a745bc77%252F
#### Version
7.0.4

**Comment by M1Aston** [comment]
This cookies is used for a number of newspapers. Fix it and kill a number of birds with one stone. :-)

**Comment by M1Aston** [comment]
It is working now, which is really good.
Unfortunately in the cookie settings social media has to be enabled\allowed, otherwise all kinds of embedded elements won't load at all. This is not the case at the moment.
I hope you can adjust this.

**Comment by wanhose** [comment]
Hi @M1Aston,

Welcome to the community, I would have liked to give you good news but I don't think there's a solution in this case. The page is doing a really hard work trying you to accept their cookies blocking all these embedded elements.

I suggest you to just accept them, or decline them (if possible). Sorry for the inconveniences.
