### ISSUE TITLE
autoweek.nl

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#614]
#### Browser
Firefox (127.0)
#### Reason
Popup showed up
#### URL
https://www.autoweek.nl/autonieuws/artikel/ook-in-nederland-kan-je-mercedes-benz-straks-zelf-van-rijstrook-wisselen/?utm_source=rss&utm_medium=rssdefault&utm_campaign=rss
#### Version
7.0.4

**Comment by M1Aston** [comment]
This wasn't fixed, the cookie message still pops up.
