### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by M1Aston** [wanhose/cookie-dialog-monster#618]
So the only way to use the latest version in FF is to load it as a temporary extension every time FF is started\launched?

**Comment by dreirund** [comment]
[&nearr;&hairsp;Seems so](https://github.com/wanhose/cookie-dialog-monster/issues/601#issuecomment-2173881110).

**Comment by M1Aston** [comment]
Well, that's awkward. 
After using this "method" for two days I have to say I'm pretty pleased with how well this extension works. But having to reinstall it every time might be too much of a hassle after a while.

**Comment by wanhose** [comment]
Hi both,

As the thread of @dreirund mentions, I'm still looking for alternatives. Sorry for the inconveniences.

**Comment by wanhose** [comment]
Hello again,

I solved this issue now, you can follow [this guide](https://github.com/wanhose/cookie-dialog-monster/tree/main/packages/browser-extension#installation-for-mozilla-firefox-users) from now on to add/update your extension if you are using Mozilla Firefox **forever**.

**Comment by dreirund** [comment]
> I solved this issue now, you can follow [this guide](https://github.com/wanhose/cookie-dialog-monster/tree/main/packages/browser-extension#installation-for-mozilla-firefox-users) from now on to add/update your extension if you are using Mozilla Firefox **forever**.

Wow. Great. Thanks. :tada: :pray: :green_heart:.

I just will now switch to this addon in my main browser, "Firefox".

**Comment by dreirund** [comment]
> *you can follow [this guide](https://github.com/wanhose/cookie-dialog-monster/tree/main/packages/browser-extension#installation-for-mozilla-firefox-users) from now on to add/update your extension if you are using Mozilla Firefox forever.*

So if you [release a new addon version on github.com](https://github.com/wanhose/cookie-dialog-monster/releases), it also updates itself/ asks for updates?

**Comment by wanhose** [comment]
> > _you can follow [this guide](https://github.com/wanhose/cookie-dialog-monster/tree/main/packages/browser-extension#installation-for-mozilla-firefox-users) from now on to add/update your extension if you are using Mozilla Firefox forever._
> 
> So if you [release a new addon version on github.com](https://github.com/wanhose/cookie-dialog-monster/releases), it also updates itself/ asks for updates?

I'm not sure but I think auto-updates won't work for now, I'll try to test it for the next release. If not, I will set up something to make easier for you to update (or get notificationes about updates.

Sorry in advance, this is just the first iteration about this issue.

**Comment by M1Aston** [comment]
Great news. I have just installed it. 
Thanks very much for your work.

**Comment by cremor** [comment]
> I solved this issue now, you can follow [this guide](https://github.com/wanhose/cookie-dialog-monster/tree/main/packages/browser-extension#installation-for-mozilla-firefox-users) from now on to add/update your extension if you are using Mozilla Firefox **forever**.

Thanks! But why does the guide say that we should download the XPI and install it from a file? When I click the download link Firefox directly asks me if I want to install the extension.

**Comment by dreirund** [comment]
On Sun, 07 Jul 2024 23:43:32 -0700, cremor ***@***.***>
wrote:

> > I solved this issue now, you can follow [this
> > guide](https://github.com/wanhose/cookie-dialog-monster/tree/main/packages/browser-extension#installation-for-mozilla-firefox-users) from now on to add/update your extension if you are using Mozilla Firefox **forever**.  
> 
> Thanks! But why does the guide say that we should download the XPI
> and install it from a file? When I click the download link Firefox
> directly asks me if I want to install the extension.

Can it depend on your configuration?

I suspect the manual "install from file" works in any case.

**Comment by cremor** [comment]
I don't know about any setting in Firefox that might change this behavior.

**Comment by wanhose** [comment]
> > I solved this issue now, you can follow [this guide](https://github.com/wanhose/cookie-dialog-monster/tree/main/packages/browser-extension#installation-for-mozilla-firefox-users) from now on to add/update your extension if you are using Mozilla Firefox **forever**.
> 
> Thanks! But why does the guide say that we should download the XPI and install it from a file? When I click the download link Firefox directly asks me if I want to install the extension.

Hi @cremor,

Thanks for the feedback, as @dreirund could be an option, your browser version or something else. I will update the installation guide to add this possible case.

Have a good evening!

**Comment by cremor** [comment]
> I'm not sure but I think auto-updates won't work for now, I'll try to test it for the next release. If not, I will set up something to make easier for you to update (or get notificationes about updates).

@wanhose As you expected, auto-updates don't work by default. But I found the documentation that explains how to enable it: https://extensionworkshop.com/documentation/manage/updating-your-extension/

**Comment by wanhose** [comment]
> > I'm not sure but I think auto-updates won't work for now, I'll try to test it for the next release. If not, I will set up something to make easier for you to update (or get notificationes about updates).
> 
> @wanhose As you expected, auto-updates don't work by default. But I found the documentation that explains how to enable it: https://extensionworkshop.com/documentation/manage/updating-your-extension/

The thing is... it's uploaded to AMO, it's not published to the store but it's there. I will investigate further to see what's happening, and then follow that guide.

Thank you so much @cremor for your contribution! 🏅
