### ISSUE TITLE
https://nordvpn.com/de/ shows a cookie selection banner overlay

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#620]
https://nordvpn.com/de/ Shows a cookie selection banner overlay:

---

![image](https://github.com/wanhose/cookie-dialog-monster/assets/1590519/51807d81-e165-43a6-a168-c1f43fd2c04f)

---

Regards!

(P.S.: (How) can I report from within the extension?)

**Comment by wanhose** [comment]
Hey @dreirund,

Thanks for the report, you certainly can report directly through the extension right-clicking anywhere in the page, then you'll see some options to play with:

![image](https://github.com/wanhose/cookie-dialog-monster/assets/50265843/2fa6727a-261c-47aa-b86e-92694f79d118)

Just uploaded a change to database, so this popup will disappear in your next reboot. Nice to see you active around here again!

**Comment by wanhose** [comment]
Hi @dreirund,

Is this issue solved?

**Comment by dreirund** [comment]
> *Is this issue solved?*

Yes.

**Comment by dreirund** [comment]
> *Is this issue solved?*

Yes.

(But I just do not understand why a reboot is necessary -- addon update should suffice: "*[so this popup will disappear right after your next reboot.](#issuecomment-2195666745)*

**Comment by wanhose** [comment]
> > _Is this issue solved?_
> 
> Yes.
> 
> (But I just do not understand why a reboot is necessary -- addon update should suffice: "_[so this popup will disappear right after your next reboot.](#issuecomment-2195666745)_

The reason is we host the database in files in this own repository. For performance and workload purposes the database is only fetched once when you first enter to the browser. So unless you fully close your browser (that sometimes is complicated due background services) or reboot your computer the database is not fetched again, so you are not be able to see these fixes until that moment.

Sorry for the inconveniences 😅

**Comment by dreirund** [comment]
On Sun, 07 Jul 2024 04:44:25 -0700, wanhose ***@***.***>
wrote:

> > (But I just do not understand why a reboot is necessary -- addon
> > update should suffice: "_[so this popup will disappear right after your next reboot.](#issuecomment-2195666745)_  
> 
> The reason is we host the database in files in this own repository.
> For performance and workload purposes the database is only fetched
> once when you first enter to the browser. So unless you fully close
> your browser (that sometimes is complicated due background services)
> or reboot your computer the database is not fetched again, so you are
> not be able to see these fixes until that moment.

So then (full) browser restart is the better term you should use. (Is the database not included in the addon, so when the addon itself gets updated that has no influence on the database?)

(I do not keep browser background processes around anyway.)

If it is as you write, then I suggest an option for the user to manually refresh the database, and the (opt-in) option to check the database in a regular interval (configurable, set a minimum that is fine for your servers) for updates (do you have a version counter or hash sum the addon can compare?) and download when there is something new.

What in fact I usually do is hibernating the laptop, and not closing my browser at all, for long times.

**Comment by wanhose** [comment]
> On Sun, 07 Jul 2024 04:44:25 -0700, wanhose ***@***.***> wrote: > (But I just do not understand why a reboot is necessary -- addon > update should suffice: "_[so this popup will disappear right after your next reboot.](#issuecomment-2195666745)_ The reason is we host the database in files in this own repository. For performance and workload purposes the database is only fetched once when you first enter to the browser. So unless you fully close your browser (that sometimes is complicated due background services) or reboot your computer the database is not fetched again, so you are not be able to see these fixes until that moment.
> So then (full) browser restart is the better term you should use. (Is the database not included in the addon, so when the addon itself gets updated that has no influence on the database?) (I do not keep browser background processes around anyway.) If it is as you write, then I suggest an option for the user to manually refresh the database, and the (opt-in) option to check the database in a regular interval (configurable, set a minimum that is fine for your servers) for updates (do you have a version counter or hash sum the addon can compare?) and download when there is something new. What in fact I usually do is hibernating the laptop, and not closing my browser at all, for long times.

Yes, I wanted to avoid to update the extension with each fix I uploaded (this takes some days for the stores to review and that) so, it sounds like a good solution for cases like yours. Let me think about how to set up this and I will send you a message when it's ready.

Thanks for the suggestion! 🚀

**Comment by wanhose** [comment]
Hi @dreirund,

I just wanted to update you about your suggestion. I've just released the version `7.1.0` that will allow you to refetch/update the database manually without needing to reboot/reload your computer every time. You will have an option inside the extension menu, you can click on the refresh icon to trigger this action.

![image](https://github.com/user-attachments/assets/0876d611-cf12-49b2-8d44-be40cf6467f9)

Thanks again!
