### ISSUE TITLE
public broadcasters

### ISSUE THREAD

**Issue by M1Aston** [wanhose/cookie-dialog-monster#640]
Recently omroepbrabant.nl was added.

There are a number of other public broadcasters  that seem to be using the same cookie (system) for their websites.
For some of them the cookie is taken care of, but only after reloading the page.
https://www.gld.nl/
https://www.rtvoost.nl/
https://www.omroepwest.nl/
https://www.omropfryslan.nl/fy
https://www.rtvnoord.nl/
https://www.rtvdrenthe.nl/
https://www.rtvutrecht.nl/
https://www.nhnieuws.nl/
https://www.rijnmond.nl/
https://www.omroepzeeland.nl/
https://www.l1.nl/

Unfortunately, I am bumping into the same problem as with some other websites when using CDM. 
If not all elements in the cookie settings\options are explicitly accepted, some elements will be missing from these sites. And that is exactly what happens.

**Comment by wanhose** [comment]
Hi @M1Aston,

I've been looking for an hour for a solution here, not found yet. I strongly recommend you to accept cookies temporarilly while I find a solution.

Sorry for the inconveniences 😰

**Comment by M1Aston** [comment]
Alright, take your time. :-)

**Comment by wanhose** [comment]
> Alright, take your time. :-)

Hi @M1Aston,

Bad news, I'm not able to inject the necessary script to allow the content to show due content security policies. I suggest you to disable the extension, then accept or reject their cookies.

Sorry for the inconveniences 😓
