### ISSUE TITLE
consent.google.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#643]
#### Browser
Firefox (128.0)
#### Reason
Popup showed up
#### URL
https://consent.google.de/m?continue=https://www.google.de/maps?f%3Dq%26hl%3Dde%26q%3D0.000000,0.000000%26ie%3DUTF8%26z%3D14%26iwloc%3Daddr%26om%3D1&gl=DE&m=0&pc=m&uxe=eomtm&cm=2&hl=de&src=1
#### Version
7.0.4

**Comment by dreirund** [comment]
While trying to open [`http://maps.google.de/maps?f=q&hl=de&q=0.000000,0.000000&ie=UTF8&z=14&iwloc=addr&om=1`](http://maps.google.de/maps?f=q&hl=de&q=0.000000,0.000000&ie=UTF8&z=14&iwloc=addr&om=1), a cookie dialogue appeared:

---

![image](https://github.com/wanhose/cookie-dialog-monster/assets/1590519/12e0c9b6-0a7c-4900-a91a-b788152f10e0)

---

**Comment by wanhose** [comment]
Hey @dreirund,

We need to work in this page, Google did a good work avoiding us to select buttons, dialogs, etc.

This issue will probably need some code and then an update. Thanks anyway, I'll keep you posted!

**Comment by dreirund** [comment]
Actually, the (for several months not updated) addon "[I still don't care about cookies](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies)" handles google sites well.

Maybe you can have a look there how they solve it?

Regards!

**Comment by wanhose** [comment]
> Actually, the (for several months not updated) addon "[I still don't care about cookies](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies)" handles google sites well.
> 
> Maybe you can have a look there how they solve it?
> 
> Regards!

Hey @dreirund,

This should be fixed now, please update to `7.1.1` when available (if you are installing it from a store, they are still pending for review by the store teams).

Let me know if it works for you 👀

**Comment by dreirund** [comment]
> *Let me know if it works for you 👀*

I can confirm that it is fixed now

**Comment by dreirund** [comment]
> *Popup shows up when visiting [news.google.de](https://news.google.de/) - used to work before*

I can confirm.

Addon version 7.2.3, database version 1725700173038.

**Comment by wanhose** [comment]
> > _Popup shows up when visiting [news.google.de](https://news.google.de/) - used to work before_
> 
> I can confirm.
> 
> Addon version 7.2.3, database version 1725700173038.

Hi @dreirund,

You are right. This was a regression, database version `>= 1725777170641` should fix it.

Sorry for the inconveniences 🙏
