### ISSUE TITLE
dbmobil.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#644]
#### Browser
Firefox (128.0)
#### Reason
Popup showed up
#### URL
https://dbmobil.de/pages/infotainment/stream/3xqJUpCKSEhgOn2CHaf6CU
#### Version
7.0.4

**Comment by dreirund** [comment]
---

![image](https://github.com/wanhose/cookie-dialog-monster/assets/1590519/8edf7322-a038-4b24-b1c8-6e4e7e68f153)

---

**Comment by dreirund** [comment]
Also on https://regio-guide.de/pages/infotainment -- seems similar:

---

![image](https://github.com/wanhose/cookie-dialog-monster/assets/1590519/6ad34edb-83a4-4147-9be9-36b0f2fa98e4)

---

**Comment by wanhose** [comment]
Hi @dreirund,

It should be fixed right after your next full browser reload/computer reboot. Feel free to close the issue when you check if the fix is working for you.

Thanks again for your feedback!

**Comment by wanhose** [comment]
Hi @dreirund,

This problem should be fixed with the version `7.1.0` that is being uploaded. Please, check if it's working for you when you update to the new version.

Thanks! 😃

**Comment by dreirund** [comment]
> *This should be fixed*

I can confirm, you can close this issue.
