### ISSUE TITLE
bahnhof.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#675]
#### Browser
Firefox (128.0)
#### Reason
Page is not responding
#### URL
https://www.bahnhof.de/sagehorn/karte
#### Version
7.0.4

**Comment by dreirund** [comment]
Needed to reload to make scrolling possible.

**Comment by wanhose** [comment]
Hi @dreirund,

This problem should be fixed with the version `7.1.0` that is being uploaded. Please, check if it's working for you when you update to the new version.

Thanks! 😃

**Comment by dreirund** [comment]
Sometimes, when I open the URL in a background tab, and only switch later to it, a cookie selection dialogue is shown and the addon's badge shows no counter.

When reloading the page (and sometimes, already when switching to the tab) the dialogue goes away and the addon's icon shows a "1" badge.

---

![image](https://github.com/user-attachments/assets/bb47a589-d90e-48ed-87be-ca0c692141f1)

**Comment by wanhose** [comment]
That's weird, I can't reproduce the issue when directly opening the page. It shows for a second after opening the page that was for a bit in the background, it's true but it satisfies the acceptance criteria for performance issues (cases when you open 100 pages at once).

There was an issue about that, so I can only apply fixes if you are in front of the page unless we want our computers to explode haha.

Anyway, I'll keep an eye on this but I don't think I can do anything else here.

**Comment by dreirund** [comment]
For me it also seems fixed now.
