### ISSUE TITLE
post-modern.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#677]
#### Browser
Firefox (128.0)
#### Reason
Popup showed up
#### URL
https://www.post-modern.de/privatkunden/brief-post-versand/
#### Version
7.0.4

**Comment by dreirund** [comment]
In the lower right corner:

---

![image](https://github.com/user-attachments/assets/4b78dc8c-1b22-4dfb-a2c6-faa916df3c16)

---

**Comment by wanhose** [comment]
Hi @dreirund,

This should be fixed now, update the database once and try again.

Thank you for your feedback 🥇

**Comment by dreirund** [comment]
> *This should be fixed now*

I can confirm.
