### ISSUE TITLE
mobility.siemens.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#678]
#### Browser
Firefox (128.0)
#### Reason
Page is not responding
#### URL
https://www.mobility.siemens.com/ch/de/unternehmen/newsroom/vectron-mit-xload-beweist-in-der-schweiz-seine-enorme-zugkraft.html
#### Version
7.0.4

**Comment by dreirund** [comment]
No scrollbars shown, no scrolling possible.

Needed to reload the page, then scrollbars appeared and scrolling was possible.

**Comment by wanhose** [comment]
Hi @dreirund,

This problem should be fixed with the version `7.1.0` that is being uploaded. Please, check if it's working for you when you update to the new version.

Thanks! 😃

**Comment by dreirund** [comment]
> *This should be fixed*

I can confirm, you can close this issue.
