### ISSUE TITLE
kleinanzeigen.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#679]
#### Browser
Firefox (128.0)
#### Reason
Popup showed up
#### URL
https://www.kleinanzeigen.de/p-anzeige-aufgeben-schritt2.html
#### Version
7.0.4

**Comment by dreirund** [comment]
Did randomly show a cookie dialogue, after the page did update itself after I entered the title of the item I want to sell.

---

![image](https://github.com/user-attachments/assets/7ca51ec7-291b-467b-8c82-b455440681be)

---

**Comment by wanhose** [comment]
Hi @dreirund,

For me it's not happening anymore. Can you confirm?

Thanks! 💯

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Firefox (130.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://www.kleinanzeigen.de/p-anzeige-aufgeben-schritt2.html
#### 🏷️ Version
7.1.5.1

**Comment by dreirund** [comment]
> *For me it's not happening anymore. Can you confirm?*

When I open it in a background tab, the issue is still there.

Reloading gives a screen with an overlay that darkens the whole site (but without the popup); the addon's icon shows a "1" badge.

**Comment by wanhose** [comment]
Hi @dreirund,

This isn't happening for me anymore with version `7.2.2`. Please, update your extension and try again.

Have a good day! 🌞

**Comment by dreirund** [comment]
> *This isn't happening for me anymore with version `7.2.2`.*

I can confirm that it is fixed now.
