### ISSUE TITLE
hsb-wr.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#680]
#### Browser
Firefox (128.0)
#### Reason
Popup showed up
#### URL
https://www.hsb-wr.de/Aktuelles/Aktuelle-Fahrplanaenderungen/
#### Version
7.0.4

**Comment by dreirund** [comment]
Cookie selection dialogue showed up, after this page was opened in a new tab from https://www.hsb-wr.de/Fahrplan-Tarife/Fahrplaene/Herbstfahrplan/ (which did not show a dialogue).

Reloading and the dialogue did disappear again.

---

![image](https://github.com/user-attachments/assets/1d56ba6e-a157-4902-a444-7532f8140a85)

---

**Comment by wanhose** [comment]
Hi @dreirund,

This problem should be fixed with the version `7.1.0` that is being uploaded. Please, check if it's working for you when you update to the new version.

Thanks! 😃

**Comment by dreirund** [comment]
> *This should be fixed*

I can confirm, you can close this issue.
