### ISSUE TITLE
pocketnavigation.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#683]
#### Browser
Firefox (128.0)
#### Reason
Page is not responding
#### URL
https://www.pocketnavigation.de/2017/08/top-outdoor-navis-test/
#### Version
7.0.4

**Comment by dreirund** [comment]
Needed to reload to make scrolling possible.

**Comment by wanhose** [comment]
Hi @dreirund,

There are cases like this where the popup removal is delayed until the page internally loads. This is an expected behaviour in a few sites like this one so I'm going to close the issue. Feel free to add more information if needed.

Sorry for the inconveniences.

**Comment by wanhose** [comment]
Hi @dreirund,

This problem should be fixed with the version `7.1.0` that is being uploaded. Please, check if it's working for you when you update to the new version.

Thanks! 😃

**Comment by dreirund** [comment]
> *This should be fixed*

I can confirm, you can close this issue.
