### ISSUE TITLE
gpspower.net

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#684]
#### Browser
Firefox (128.0)
#### Reason
Popup showed up
#### URL
https://www.gpspower.net/igo-primo-software-tools/334766-becker-active-5-lmu.html
#### Version
7.0.4

**Comment by dreirund** [comment]
Normally, https://www.gpspower.net/ did not show cookie selection dialogue, but now it did once:

---

![image](https://github.com/user-attachments/assets/f8224173-540a-45ad-9f65-b74a1ef222e3)

**Comment by wanhose** [comment]
Hi @dreirund,

Please, update to the next `7.1.0` version when available. There's no issue on my end using this new version.

**Comment by dreirund** [comment]
Please close this, as I cannot observe an issue now.
