### ISSUE TITLE
digital-eliteboard.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#685]
#### Browser
Firefox (128.0)
#### Reason
Popup showed up
#### URL
https://www.digital-eliteboard.com/threads/navigationsprogramme-800x480-fur-7-6-5-inch-gerate-mit-wince-resident-flash-sdmmc.310086/
#### Version
7.0.4

**Comment by dreirund** [comment]
![image](https://github.com/user-attachments/assets/0cc8bfb0-a407-4f57-bdfb-3f80e3df8a40)

**Comment by wanhose** [comment]
> ![image](https://private-user-images.githubusercontent.com/1590519/350787345-0cc8bfb0-a407-4f57-bdfb-3f80e3df8a40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDI0NzUsIm5iZiI6MTcyNTEwMjE3NSwicGF0aCI6Ii8xNTkwNTE5LzM1MDc4NzM0NS0wY2M4YmZiMC1hNDA3LTRmNTctYmRmYi0zZjgwZTNkZjhhNDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MzFUMTEwMjU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjM4ZWQwYTFmOGE0MGJjNmU1MDE4NjQ5ZGY3YTA3MmY5NzY2ZDEyZDQ1NGVhZmJmZTE1ZDI5NDNkMmU4NDExMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jjnmsxMEy2hGKE8VGng8VO9_R2x-L2ZJ_WalUZWzYdo)

Hi @dreirund,

This issue was fixed in `7.2.2`, so please update your extension manually. I've also added auto-updates from `7.2.1` so you won't need to do this anymore.

Thanks again for your contributions to the project! 🍾

**Comment by dreirund** [comment]
> *This issue was fixed in `7.2.2`*

I can confirm that it is fixed now.
