### ISSUE TITLE
hellerau.org

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#687]
#### Browser
Firefox (128.0)
#### Reason
Popup showed up
#### URL
https://www.hellerau.org/de/hellerau-card/
#### Version
7.0.4

**Comment by dreirund** [comment]
![image](https://github.com/user-attachments/assets/45dc23b8-8379-4502-8da5-863b2de14390)

**Comment by wanhose** [comment]
Hi @dreirund,

This should be fixed now, update the database once and try again.

Thank you for your feedback 🥇

**Comment by dreirund** [comment]
Seems to be fixed now. You can close this issue.
