### ISSUE TITLE
naturzeit.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#690]
#### Browser
Firefox (129.0)
#### Reason
Popup showed up
#### URL
https://www.naturzeit.com/relags-weithalstonne-volumen-in-liter-26/1002843
#### Version
7.0.4

**Comment by dreirund** [comment]
Cookie selection dialogue appeared on first load (in background tab).

Had to reaload page to make this go away (and make this addon recognise the page).

---

![image](https://github.com/user-attachments/assets/ff097ef9-7a83-41ef-8ec4-e1773024d2d8)

**Comment by dreirund** [comment]
While browsing to [`https://www.naturzeit.com/relags-weithalstonne-volumen-in-liter-68-5/1002844`](https://www.naturzeit.com/relags-weithalstonne-volumen-in-liter-68-5/1002844) by clicking on the corresponding element on [the originating website](https://www.naturzeit.com/relags-weithalstonne-volumen-in-liter-26/1002843), the cookie selection dialogue reappeared:

---

![image](https://github.com/user-attachments/assets/52a22182-543c-43fd-ab35-5ed7639a45e7)

**Comment by wanhose** [comment]
Hi @dreirund,

This should be fixed now, update the database once and try again.

Thank you for your feedback 🥇

**Comment by dreirund** [comment]
I can confirm that it is fixed now. You can close this issue.
