### ISSUE TITLE
spieletastisch.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#693]
#### Browser
Firefox (129.0)
#### Reason
Popup showed up
#### URL
https://www.spieletastisch.de/
#### Version
7.0.4

**Comment by dreirund** [comment]
Popup shows up despite that the addon is displaying a "1" counter.

---

![image](https://github.com/user-attachments/assets/483dc653-6ebd-41dc-b8f5-9472004401ed)

**Comment by wanhose** [comment]
Hi @dreirund,

This should be fixed now, if not please wait until `7.1.0` is published.

Thanks again 😄

**Comment by dreirund** [comment]
> *This should be fixed now*

I can confirm, you can close this issue.
