### ISSUE TITLE
nic.ru

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#697]
#### Browser
Chrome (100.0.4896.127)
#### Reason
Popup showed up
#### URL
https://www.nic.ru/catalog/domains/?searchWord=exit
#### Version
7.0.2

**Comment by dreirund** [comment]
I can confirm this on Firefox:

---

![image](https://github.com/user-attachments/assets/d6c69e5c-f998-48e6-9427-c8b511daef6c)

**Comment by wanhose** [comment]
Hi @dreirund,

This should be fixed now, if not please wait until `7.1.0` is published.

Thanks again 😄

**Comment by dreirund** [comment]
> *This should be fixed now*

I can confirm, you can close this issue.
