### ISSUE TITLE
hszg.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#699]
#### Browser
Firefox (129.0)
#### Reason
Page is not responding
#### URL
https://www.hszg.de/veranstaltungsdetails/30-internationale-elektrotechnik-olympiade-neisse-elektro
#### Version
7.0.4

**Comment by dreirund** [comment]
Loaded the page in a background tab.

As soon as I switched to the tab, a cookie selection dialogue showed for a fraction of a second, then disappeared.

Scrolling of the page was not possible.

Needed to reload the page to make scrolling possible.

**Comment by wanhose** [comment]
Hi @dreirund,

This problem should be fixed with the version `7.1.0` that is being uploaded. Please, check if it's working for you when you update to the new version.

Thanks! 😃

**Comment by dreirund** [comment]
> *This should be fixed*

I can confirm, you can close this issue.
