### ISSUE TITLE
city-bahn.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#706]
#### Browser
Firefox (129.0)
#### Reason
Popup showed up
#### URL
https://www.city-bahn.de/
#### Version
7.0.4

**Comment by wanhose** [comment]
Hi @dreirund,

This should be fixed now, if not please wait until `7.1.0` is published.

Thanks again 😄

**Comment by dreirund** [comment]
> *This should be fixed now*

I can confirm, you can close this issue.

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://www.bahn.de/
#### 🏷️ Version
7.3.0

**Comment by sonnyxq** [comment]
![Screenshot 2024-09-20 222213](https://github.com/user-attachments/assets/e4465de0-231d-45bc-b876-1255a7fadbc4)

**Comment by wanhose** [comment]
> ![Screenshot 2024-09-20 222213](https://private-user-images.githubusercontent.com/60904977/369544571-e4465de0-231d-45bc-b876-1255a7fadbc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjg1ODMsIm5iZiI6MTcyODIyODI4MywicGF0aCI6Ii82MDkwNDk3Ny8zNjk1NDQ1NzEtZTQ0NjVkZTAtMjMxZC00NWJjLWI4NzYtMTI1NWE3ZmFkYmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE1MjQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2NmI3MmM2OGEwY2UwZDI4NTgyNjhkY2ViZDA5ZmFjM2M1N2I2NDM0ZmI3NzA0ZGExYzViZGY5ZmVkNzk2NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9AOZfRog9UKg6O52zzSgF_NvWgTXkuJIQdcX8A5p1GU)

Hi @sonnyxq,

Please, update your database version to `>= 1728228200092`.

Thanks!

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Chrome (129.0.0.0)
#### 📝 Reason
This is only a test
#### 🔗 URL
https://www.city-bahn.de/
#### 🏷️ Version
7.3.3

**Comment by sonnyxq** [comment]
@wanhose Hi.

I can still reproduce it on https://www.bahn.de/
Not... https://www.city-bahn.de/

![Screenshot 2024-10-06 194424](https://github.com/user-attachments/assets/6e3d33fb-fe9e-49e1-9974-e7bd5b79ed87)

![Screenshot 2024-10-06 193214](https://github.com/user-attachments/assets/71cbc8e1-bed3-4e91-935c-2238ec5df762)

**Comment by wanhose** [comment]
> @wanhose Hi.
> 
> I can still reproduce it on https://www.bahn.de/ Not... https://www.city-bahn.de/
> 
> ![Screenshot 2024-10-06 194424](https://private-user-images.githubusercontent.com/60904977/373968045-6e3d33fb-fe9e-49e1-9974-e7bd5b79ed87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNDAyODgsIm5iZiI6MTcyODIzOTk4OCwicGF0aCI6Ii82MDkwNDk3Ny8zNzM5NjgwNDUtNmUzZDMzZmItZmU5ZS00OWUxLTk5NzQtZTdiZDViNzllZDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE4Mzk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0NmRmMDdmMWNiMjgwNzI4MjkxYTZhNTU2ODZjOGM1MTcxYTMxNTRiZTdlZGQ2M2Q3NmYyMzUyYjU4NWI4YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YLGnDB8FTdnCbwP7Ru0nnLWRpExOYzDuMG1j6SA-Htc)
> 
> ![Screenshot 2024-10-06 193214](https://private-user-images.githubusercontent.com/60904977/373967251-71cbc8e1-bed3-4e91-935c-2238ec5df762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyNDAyODgsIm5iZiI6MTcyODIzOTk4OCwicGF0aCI6Ii82MDkwNDk3Ny8zNzM5NjcyNTEtNzFjYmM4ZTEtYmVkMy00ZTkxLTkzNWMtMjIzOGVjNWRmNzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE4Mzk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZDY2ZDU4ZTkxNWY4ZTVhYjc3ZGY5NTgzYTllZTEwYzM5ZWUyZjVkM2JkZmJiMzQ4NTQwYjlhZWVhYTY1Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fiPLucX0EGbeQrhN7u1QUW7duFz8laDprSnYBGUst1k)

Hi @sonnyxq,

You have an old database version. Please, update it.

Let me know.

**Comment by sonnyxq** [comment]
@wanhose It's done! Next time I check it before.
