### ISSUE TITLE
rvl-online.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#714]
#### Browser
Firefox (129.0)
#### Reason
Popup showed up
#### URL
https://rvl-online.de/mit-dem-d-ticket-d-ticket-jugendbw-nach-frankreich/
#### Version
7.0.4

**Comment by dreirund** [comment]
Cookie selection dialogue showed up (page was opened in a background tab).

On page reload, it was gone and the addon's icon showed a badge with the number "2".

I can reproduce this on https://rvl-online.de/ when I open the page in a new tab (with cleaned cookies) in the background.

---

![image](https://github.com/user-attachments/assets/dd7801ed-8263-4922-98a5-ea04136dcf6e)

**Comment by wanhose** [comment]
> Cookie selection dialogue showed up (page was opened in a background tab).
> 
> On page reload, it was gone and the addon's icon showed a badge with the number "2".
> 
> I can reproduce this on https://rvl-online.de/ when I open the page in a new tab (with cleaned cookies) in the background.
> 
> ![image](https://private-user-images.githubusercontent.com/1590519/352802222-dd7801ed-8263-4922-98a5-ea04136dcf6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTA4MDYsIm5iZiI6MTcyMjc5MDUwNiwicGF0aCI6Ii8xNTkwNTE5LzM1MjgwMjIyMi1kZDc4MDFlZC04MjYzLTQ5MjItOThhNS1lYTA0MTM2ZGNmNmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDRUMTY1NTA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWI3NGFlNTRlNjE1MGQ2NmY2MTFhZDY3NDI5ZTIyNGU4YzI5Y2E1ZjlhZWRlNmU1NTMyOWMwY2E1YmE0ZjMyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.tMG82PRGXUMKdHRpgEptqYuQZKSNNRaH-Vw10KC5Ejw)

Hey @dreirund,

This should be fixed now, please update to `7.1.1` when available (if you are installing it from a store, they are still pending for review by the store teams).

Let me know if it works for you 👀

**Comment by dreirund** [comment]
> *Let me know if it works for you 👀*

I can confirm that it is fixed now.
