### ISSUE TITLE
voelkner.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#715]
#### Browser
Firefox (129.0)
#### Reason
Popup showed up
#### URL
https://www.voelkner.de/
#### Version
7.0.4

**Comment by dreirund** [comment]
![image](https://github.com/user-attachments/assets/b6917812-5505-411f-85cd-c9481f1636dc)

**Comment by wanhose** [comment]
Hi @dreirund,

This problem should be fixed with the version `7.1.0` that is being uploaded. Please, check if it's working for you when you update to the new version.

Thanks! 😃

**Comment by dreirund** [comment]
> *This should be fixed now*

I can confirm, you can close this issue.

**Comment by wanhose** [comment]
Hi @dreirund,

This should be fixed now, update the database once and try again.

Thank you for your feedback 🥇
