### ISSUE TITLE
Sites opened in the background often cannot be scrolled. Reload fixes it.

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#720]
Ahoj,

I see on quite a lot of sites that I open in the background that they cannot be scrolled.

No cookie dialogue either. (On some there is, though.)

Reloading the site fixes the issue.

I stopped reporting all of them; one last was https://www.tag24.de/... .

What is the underlying issue here?

Regards!

**Comment by dreirund** [comment]
Actually, the (for several months not updated) addon "[I still don't care about cookies](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies)" usually handles sites opened in the background as well (or bad) as sites opened in the foreground.

Maybe you can have a look there how they solve it?

Regards!

**Comment by wanhose** [comment]
Hi @dreirund,

This problem should be fixed with the version `7.1.0` that is being uploaded. Please, check if it's working for you when you update to the new version.

Thanks! 😃

**Comment by dreirund** [comment]
For some it is fixed, for others not (I did comment on the specific sites' issues where it is not working).
