### ISSUE TITLE
[Suggestion] Duplicate issue report detection, and ? coping with report influx when the addon gets more popular.

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#735]
Ahoj @wanhose,

I just want to make a suggestion:

The addon "[I still don't care about cookies](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies)" got quite pupular and due to the ability to report websites from within the addon, it's [issue tracker](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues) got overwhelmed.

In the end, [no more updates were made](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies/issues/10278) (it is speculation if it is due to overwhelming issue reports).

One thing which the author there introduced eventually and was helpful was detection of duplicate issue reports. Maybe this is a good idea to implement here, too, in early stage. And maybe some thinking how to cope with massive issue influx in the case this addon gets more popular would be helpful now, and not when it is too late.

Regards and many thanks for your support!  
How can one show you some recognition of your work?

Regards!

**Comment by wanhose** [comment]
Hi @dreirund,

I'm working on this, I've taken two actions already with the new version `7.1.0`.

- The API was creating issues even if they were already there but closed, so now it reopens issues if they exist (closed or not).
- The fast user who clicked twice the button to submit was able to duplicate issues, so now this is fixed.

I will apply further steps, like a bot who help me with these issues.

Thanks for the suggestion 🚀

**Comment by wanhose** [comment]
Regarding the recognition, what do you mean? PayPal or something like that? For me, having active users that give me feedback and trust on my solutions are the most important things. Even if I have to pay some costs like the API costing at the end of the month, I don't usually ask for this. But if you feel it, have a link to my [PayPal account](https://paypal.me/wanhose).

Have a great weekend! 🌴

**Comment by dreirund** [comment]
> *Regarding the recognition, what do you mean?*

If some money helps you to keep working on this, then I mean money.

Maybe you also have something else in mind. But that you already explained.

**Comment by wanhose** [comment]
Any help is welcome @dreirund. Money is an option to contribute to the infrastructure of this extension but you can always do it in many other different ways:

- Post about my work on platforms like Twitter, LinkedIn, or a relevant tech forum. Tag the project and highlight the impact or usefulness of the extension.

- Write a detailed blog post or article showcasing the extension's features, the problems it solves and/or the developer's effort.

- Leave positive reviews on the extension's official page (like the Chrome Web Store) or share testimonials on social media.

- Report any broken site as you do is another impactful way to contribute to the project.

Thanks!

**Comment by wanhose** [comment]
I've done another iteration over this issue @dreirund, it should handle now any new reports under the same issue. The problem was about some limitations in the GitHub API, but now it adds a comment for the new report with the details you sent under the same issue.

Thank you again for your feedback, it was really important to get this working!
