### ISSUE TITLE
coverd.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#739]
#### Browser
Chrome (123.0.0.0)
#### Reason
Page contains visual glitches
#### URL
https://coverd.de/pages/unser-team
#### Version
7.0.4

**Comment by wanhose** [comment]
Can't reproduce the issue here, please feel free to reopen this issue adding more information if needed.

**Comment by sonnyxq** [comment]
If you click on those two, there is. Please take a look at the screenshots.
![Screenshot 2024-08-04 173936](https://github.com/user-attachments/assets/71bde781-e069-4b71-9896-3ed62e3f35f7)
![Screenshot 2024-08-04 174006](https://github.com/user-attachments/assets/01fcdc86-79b3-4881-905f-a8f672da49ac)

**Comment by sonnyxq** [comment]
@wanhose

**Comment by wanhose** [comment]
> If you click on those two, there is. Please take a look at the screenshots. ![Screenshot 2024-08-04 173936](https://private-user-images.githubusercontent.com/60904977/354912668-71bde781-e069-4b71-9896-3ed62e3f35f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3ODcyOTQsIm5iZiI6MTcyMjc4Njk5NCwicGF0aCI6Ii82MDkwNDk3Ny8zNTQ5MTI2NjgtNzFiZGU3ODEtZTA2OS00YjcxLTk4OTYtM2VkNjJlM2YzNWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDE1NTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3YTQzZDEzNDM2ZDA5OTllMmRhMGE3YzRlOGFmNTZlOWRkODUxMmFmNTFlZGQ0MWVhNDE2NTE3ZGIzYzRmYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pnZCojjdH7HygygEg83G6b_b-Qtrdh6ZyTd_wdgEB90) ![Screenshot 2024-08-04 174006](https://private-user-images.githubusercontent.com/60904977/354912670-01fcdc86-79b3-4881-905f-a8f672da49ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3ODcyOTQsIm5iZiI6MTcyMjc4Njk5NCwicGF0aCI6Ii82MDkwNDk3Ny8zNTQ5MTI2NzAtMDFmY2RjODYtNzliMy00ODgxLTkwNWYtYThmNjcyZGE0OWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDE1NTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZmYxZTBiNDFjNTEzMWU2NTM2YjYyYTljNWI0MjU5YzJhZDcxNGZiOTQzMzAwYTFiNThkZmM4YjE2YzU3YWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cOTHQ93EdHGVMIUYemigljW_Qb8HJPA8dgQV2eKAxDQ)

Hi @sonnyxq,

Thanks for the instructions, they were very helpful to find the issue and I was able to quick fix this. I just uploaded the version `1722786792198` of the database which fixes this problem. If your extension isn't `7.1.0` yet, you can't manually force the update of your database. So you need to wait until the next reboot, or maybe fully closing the browser.

But defintely, you will see the fix soon. Please, leave here a message when you have confirmed that is working for you to close the issue.

Sorry for the inconveniences and welcome to the project!

**Comment by sonnyxq** [comment]
@wanhose 
Yes Sir, its working again. I did force the update as you mentioned it to Database version 1722786792198, Extension version 7.1.0

I am new to Github and dont know how to close this issue ticket yet :-)
Maybe please if you get the time - you could show me?

**Comment by wanhose** [comment]
> @wanhose Thank you!!! Yes Sir, its working again. I did force the update as you mentioned it to Database version 1722786792198, Extension version 7.1.0
> 
> I am new to Github and dont know how to close this issue ticket yet :-) Maybe please if you get the time - you could show me?

Glad it worked!

Regarding closing the issue, I think (as I'm the one creating the issues through the GitHub API) you can't close them... but don't worry, just drop here a message and I will do it for you!

Have a good day! 😄
