### ISSUE TITLE
akku-king.net

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#742]
#### Browser
Firefox (129.0)
#### Reason
Popup showed up
#### URL
https://www.akku-king.net/akku-king-akku-ersetzt-jbl-gsp1029102a-li-polymer-6000mah-fuer-jbl-charge-3-2016-charge-3-2016-version/mp3-player-zubehoer/akku/jbl_20115069_34574
#### Version
7.1.0

**Comment by dreirund** [comment]
I reported this with addon version 7.1.0 to repopen issue #682. But it seems that it has created a new issue instead.

**Comment by wanhose** [comment]
> I reported this with addon version 7.1.0 to repopen issue #682. But it seems that it has created a new issue instead.

Hey @dreirund,

This shouldn't be happening, there's some code that checks this in the API.

Let me have a look, will keep you posted 👀

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Firefox (130.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://www.akku-king.net/akku-king-akku-ersetzt-jbl-gsp1029102a-li-polymer-6000mah-fuer-jbl-charge-3-2016-charge-3-2016-version/mp3-player-zubehoer/akku/jbl_20115069_34574
#### 🏷️ Version
7.1.5.1

**Comment by dreirund** [comment]
Still ...

---

![image](https://github.com/user-attachments/assets/ca8a07fb-85cb-4508-94a4-047fed28aacd)

---

**Comment by wanhose** [comment]
> Still ...
> 
> ![image](https://private-user-images.githubusercontent.com/1590519/361255398-ca8a07fb-85cb-4508-94a4-047fed28aacd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwMDM0MjIsIm5iZiI6MTcyNjAwMzEyMiwicGF0aCI6Ii8xNTkwNTE5LzM2MTI1NTM5OC1jYThhMDdmYi04NWNiLTQ1MDgtOTRhNC0wNDdmZWQyOGFhY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMjExODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjAzZWUxZDhlNjE1MDc4M2NlODZiNTNiNzhiZmYzMjkxZGYzNzJiNmRhM2QyNTAzY2M2YTlmNzQ5ZTU2Y2YyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.MEnhY0GyWRFawDHI5uCRE1UgRR0KrUcH6wBXMZxeyRo)

Hi @dreirund,

https://github.com/user-attachments/assets/09ac70eb-b9b1-4208-a918-37baac436090

Can't reproduce the issue with the latest version `7.2.4`. Please, update your extension and try again. Feel free to add more information.

Thanks for your feedback!

**Comment by dreirund** [comment]
> *Can't reproduce the issue with the latest version `7.2.4`*

Yes, issue seems to be gone.
