### ISSUE TITLE
thingiverse.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#745]
#### Browser
Firefox (128.0)
#### Reason
Popup showed up
#### URL
https://www.thingiverse.com/
#### Version
7.1.0

**Comment by dreirund** [comment]
For me, as soon as I switch to the loaded tab, the CPU goes on full power for a few seconds, and then the cookie selection dialogue disappears.

**Comment by dreirund** [comment]
I can confirm that it works now for me.
