### ISSUE TITLE
sellerforum.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#752]
#### Browser
Firefox (129.0)
#### Reason
Popup showed up
#### URL
https://www.sellerforum.de/forum/thread/62606-dhl-wer-entscheidet-eigentlich-%C3%BCber-eine-automatische-zweitzustellung/
#### Version
7.1.0

**Comment by dreirund** [comment]
![image](https://github.com/user-attachments/assets/4ff8b861-681f-4dc6-955a-16a77b4e3171)

---

Note: For "simple" cases, please close the issues yourself after fixing them; I do not want anymore to provide feedback for every solved case.

**Comment by wanhose** [comment]
> ![image](https://private-user-images.githubusercontent.com/1590519/355247096-4ff8b861-681f-4dc6-955a-16a77b4e3171.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4OTQzMTQsIm5iZiI6MTcyMjg5NDAxNCwicGF0aCI6Ii8xNTkwNTE5LzM1NTI0NzA5Ni00ZmY4Yjg2MS02ODFmLTRkYzYtOTU1YS0xNmE3N2I0ZTMxNzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDVUMjE0MDE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhhZWFiZjUyMDM1MzA2MTE1ODg1YmE2MTNiYzI3NGRhNTJmZTNlMWMyYWUyNDAyYzQzMGNlNGI3OTI5NjIxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Xsa1yEiCoDd0V0zbhcXmZkES82VvT7svSxA2ES68hqA)
> 
> Note: For "simple" cases, please close the issues yourself after fixing them; I do not want anymore to provide feedback for every solved case.

Sure, no problem. Sorry for the inconveniences.

**Comment by wanhose** [comment]
This dialog is the only element in the DOM that isn't triggering a mutation for itself or its container. This is an edge-case that we will review again soon.

**Comment by dreirund** [comment]
> *This is an edge-case that we will review again soon.*

OK! (For now, it still persists, but the issue is still open, too.)

Anyway, thanks for your great and responsive work on the issues here!,  
regards.

**Comment by wanhose** [comment]
Hi @dreirund,

Fixed with database version `>= 1725177498323`, please update.

Thanks for your feedback! 😃

**Comment by dreirund** [comment]
> *Fixed with database version `>= 1725177498323`, please update.*

I can confirm that it is fixed now.
