### ISSUE TITLE
new.reddit.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#753]
#### Browser
Firefox (129.0)
#### Reason
Popup showed up
#### URL
https://new.reddit.com/message/messages
#### Version
7.1.0

**Comment by dreirund** [comment]
Coming from https://new.reddit.com/new, there clicking on the "bell" symbol and opening the [private messages view](https://new.reddit.com/message/messages), I see the following cookie banner at the bottom. And the addon's icon shows a "1" badge.

This is regardless weather I open it in the background or in the foreground.

When I directly put https://new.reddit.com/message/messages in the browser's URL bar I usually also get the banner, even when I directly open it in the foreground.

---

![image](https://github.com/user-attachments/assets/8c9fa95a-cb43-4ace-ad38-62a18ac0817a)

**Comment by dreirund** [comment]
I can confirm that it works now for me.
