### ISSUE TITLE
rsu.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#758]
#### Browser
Chrome (123.0.0.0)
#### Reason
Popup showed up
#### URL
https://www.rsu.de/s/kfz-teile/ol/motorol?filter=stock_2
#### Version
7.1.1

**Comment by sonnyxq** [comment]
@wanhose Hi there. The issue is still there with your extension. I reported this cookie pop-up here with you and Adguard. What I mean is... Please take a look at the screenshot here I shared: https://github.com/AdguardTeam/AdguardFilters/issues/185843

**Comment by wanhose** [comment]
Hi again @sonnyxq,

I think you should update to the latest version, can't reproduce this issue with our latest version `7.1.4`.

https://github.com/user-attachments/assets/0ab8bb26-ba00-4f9c-88d1-341bf022a932

**Comment by wanhose** [comment]
This issue about the buttons is still happening, I'm going to revert the changes @sonnyxq. This needs some extra work to remove that dialog. Sorry for the inconveniences.

**Comment by wanhose** [comment]
Same problem as #783.

**Comment by wanhose** [comment]
Please, update to database version >= "1724484573187".

**Comment by sonnyxq** [comment]
@wanhose Thank you for working on this website. As you know, I mentioned above that I reported this cookie pop-up with you here and Adguard team. And right I found a bug. Please take a look.

Your extension:
![Animation1](https://github.com/user-attachments/assets/bc82abc2-df17-4789-b2ae-9bf0067f9247)

Adguard:
![Animation2](https://github.com/user-attachments/assets/532a9b32-9108-478a-94d5-30967fd2a896)

**Comment by sonnyxq** [comment]
@wanhose I guess you didnt notice this one here from 25. Aug.

**Comment by wanhose** [comment]
> @wanhose Thank you for working on this website. As you know, I mentioned above that I reported this cookie pop-up with you here and Adguard team. And I found a bug.
> 
> Please take a look. Those two are .GIF
> 
> Your extension: ![Animation1](https://private-user-images.githubusercontent.com/60904977/361260753-bc82abc2-df17-4789-b2ae-9bf0067f9247.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjQwNTcsIm5iZiI6MTcyNTI2Mzc1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjEyNjA3NTMtYmM4MmFiYzItZGYxNy00Nzg5LWIyYWUtOWJmMDA2N2Y5MjQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA3NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZTVmZmZiYTA1ZjgyNmZjYjViZDllMTBmYjYyNzJhNjg4MWEwMzJkNzljNjQyNDI2ZjBjYWRhMjVmNzM5OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQ6U9k2GhLXkhvN7tnsRoTmZBBO07UrAjHLD8qtT-bc) [ ![Animation1](https://private-user-images.githubusercontent.com/60904977/361260753-bc82abc2-df17-4789-b2ae-9bf0067f9247.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjQwNTcsIm5iZiI6MTcyNTI2Mzc1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjEyNjA3NTMtYmM4MmFiYzItZGYxNy00Nzg5LWIyYWUtOWJmMDA2N2Y5MjQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA3NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZTVmZmZiYTA1ZjgyNmZjYjViZDllMTBmYjYyNzJhNjg4MWEwMzJkNzljNjQyNDI2ZjBjYWRhMjVmNzM5OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQ6U9k2GhLXkhvN7tnsRoTmZBBO07UrAjHLD8qtT-bc) ](https://private-user-images.githubusercontent.com/60904977/361260753-bc82abc2-df17-4789-b2ae-9bf0067f9247.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjQwNTcsIm5iZiI6MTcyNTI2Mzc1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjEyNjA3NTMtYmM4MmFiYzItZGYxNy00Nzg5LWIyYWUtOWJmMDA2N2Y5MjQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA3NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZTVmZmZiYTA1ZjgyNmZjYjViZDllMTBmYjYyNzJhNjg4MWEwMzJkNzljNjQyNDI2ZjBjYWRhMjVmNzM5OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQ6U9k2GhLXkhvN7tnsRoTmZBBO07UrAjHLD8qtT-bc) [ ](https://private-user-images.githubusercontent.com/60904977/361260753-bc82abc2-df17-4789-b2ae-9bf0067f9247.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjQwNTcsIm5iZiI6MTcyNTI2Mzc1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjEyNjA3NTMtYmM4MmFiYzItZGYxNy00Nzg5LWIyYWUtOWJmMDA2N2Y5MjQ3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA3NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZTVmZmZiYTA1ZjgyNmZjYjViZDllMTBmYjYyNzJhNjg4MWEwMzJkNzljNjQyNDI2ZjBjYWRhMjVmNzM5OTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yQ6U9k2GhLXkhvN7tnsRoTmZBBO07UrAjHLD8qtT-bc)
> 
> Adguard: ![Animation2](https://private-user-images.githubusercontent.com/60904977/361260758-532a9b32-9108-478a-94d5-30967fd2a896.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjQwNTcsIm5iZiI6MTcyNTI2Mzc1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjEyNjA3NTgtNTMyYTliMzItOTEwOC00NzhhLTk0ZDUtMzA5NjdmZDJhODk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA3NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ODU3ZDE5Y2Q1MzlhNmQ3ZWU1OTM5OTUwMGQ5YTRjMmJjYzQxNDA3YjMxMTc3NWZmMjk4NjdjNTM3OGJjNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wmJpm7P65t7m6M7q60PuuuSuCGhDICOSb_QNvVGf-Jc) [ ![Animation2](https://private-user-images.githubusercontent.com/60904977/361260758-532a9b32-9108-478a-94d5-30967fd2a896.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjQwNTcsIm5iZiI6MTcyNTI2Mzc1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjEyNjA3NTgtNTMyYTliMzItOTEwOC00NzhhLTk0ZDUtMzA5NjdmZDJhODk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA3NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ODU3ZDE5Y2Q1MzlhNmQ3ZWU1OTM5OTUwMGQ5YTRjMmJjYzQxNDA3YjMxMTc3NWZmMjk4NjdjNTM3OGJjNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wmJpm7P65t7m6M7q60PuuuSuCGhDICOSb_QNvVGf-Jc) ](https://private-user-images.githubusercontent.com/60904977/361260758-532a9b32-9108-478a-94d5-30967fd2a896.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjQwNTcsIm5iZiI6MTcyNTI2Mzc1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjEyNjA3NTgtNTMyYTliMzItOTEwOC00NzhhLTk0ZDUtMzA5NjdmZDJhODk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA3NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ODU3ZDE5Y2Q1MzlhNmQ3ZWU1OTM5OTUwMGQ5YTRjMmJjYzQxNDA3YjMxMTc3NWZmMjk4NjdjNTM3OGJjNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wmJpm7P65t7m6M7q60PuuuSuCGhDICOSb_QNvVGf-Jc) [ ](https://private-user-images.githubusercontent.com/60904977/361260758-532a9b32-9108-478a-94d5-30967fd2a896.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyNjQwNTcsIm5iZiI6MTcyNTI2Mzc1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjEyNjA3NTgtNTMyYTliMzItOTEwOC00NzhhLTk0ZDUtMzA5NjdmZDJhODk2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAyVDA3NTU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ODU3ZDE5Y2Q1MzlhNmQ3ZWU1OTM5OTUwMGQ5YTRjMmJjYzQxNDA3YjMxMTc3NWZmMjk4NjdjNTM3OGJjNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wmJpm7P65t7m6M7q60PuuuSuCGhDICOSb_QNvVGf-Jc)

Hey @sonnyxq,

I'll allocate some time for this soon, let's see what we can do because this page is very fragile.

Thanks for the reminder! 👍

**Comment by wanhose** [comment]
Hi @sonnyxq,

Please, update your database version to `>= 1726394569113` and try again.

Have a good day 😄
