### ISSUE TITLE
dhl.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#762]
#### Browser
Firefox (129.0)
#### Reason
Page is not responding
#### URL
https://www.dhl.de/de/privatkunden/kundenkonto/willkommen.html
#### Version
7.1.0

**Comment by dreirund** [comment]
When in logged-in state, it infinetely cycles (and reloads) between https://www.dhl.de/de/privatkunden.html and https://www.dhl.de/de/privatkunden.html.

**Comment by wanhose** [comment]
> When in logged-in state, it infinetely cycles (and reloads) between https://www.dhl.de/de/privatkunden.html and https://www.dhl.de/de/privatkunden.html.

Hi @dreirund,

Please, update to `7.1.1` where this issue was solved.

**Comment by dreirund** [comment]
I can confirm that it works now for me.
