### ISSUE TITLE
flux.at

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#776]
#### Browser
Firefox (129.0)
#### Reason
Cannot click
#### URL
https://flux.at/
#### Version
7.1.3

**Comment by cremor** [comment]
The dialog which should show after clicking on the map in the lower part of the page is incorrectly blocked.

**Comment by wanhose** [comment]
> The dialog which should show after clicking on the map in the lower part of the page is incorrectly blocked.

Hey @cremor,

Thanks for the feedback, you're right. I've just uploaded a fix, so please upgrade to any version after (or equal) the database version `1723359332975`.

Have a good day!
