### ISSUE TITLE
technomarket.bg

### ISSUE THREAD

**Issue by Rusenche** [wanhose/cookie-dialog-monster#783]
Hi my friend @wanhose

I ran into a strange problem that I'm sure is caused by your remarkable `Cookie dialog monster` extension.

![ffff](https://github.com/user-attachments/assets/b42d7bd0-8852-4eef-b1d9-e49e3fc27445)

Steps to reproduce the issue:
1. Open https://www.technomarket.bg/telefoni/samsung-galaxy-s24-ultra-5g-256gb-ds-gray-s928-09219552
2. Try to type in the search field of the site - it is impossible until your wonderful extension is blocked.

I tested with version **7.0.4** and with the latest version - **7.1.4** - the problem is there.

I hope you fix it soon. ;)

Thank you my friend.

**Comment by wanhose** [comment]
> @wanhose, am I to understand that the fix to hide the bottom bar that I showed in the picture in my previous post will be available in the next version of the program? Because currently the topic is closed as solved, but the problem is still not solved.

Exactly @Rusenche, as soon as you update to `7.1.5`. 😄

**Comment by wanhose** [comment]
> @wanhose, version 7.1.5 is not here: https://chrome.google.com/webstore/detail/cookie-dialog-monster/djcbfpkdhdkaflcigibkbpboflaplabg/
> 
> Although it seems that version 7.1.5 is not considered stable because it is not reflected here as such and is not among the stable versions: ![latest](https://private-user-images.githubusercontent.com/18578128/361305072-1cca8ae0-041c-406e-a145-01f8e8e7e560.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDc0MjAsIm5iZiI6MTcyNDY0NzEyMCwicGF0aCI6Ii8xODU3ODEyOC8zNjEzMDUwNzItMWNjYThhZTAtMDQxYy00MDZlLWExNDUtMDFmOGU4ZTdlNTYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA0Mzg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5NmU5ZDNhNDFhNTExNmEyNzc5MjI2M2MwNzI3ZWVhYmI0NWZhYjEwNWVjZWUxZWJlZTFiMjU3ZTJmNTcwN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Sg6ks38D1idKEU74SW-FgIs_1AD3vg-fGKATIcSt6E0)
> 
> But if we go directly to https://github.com/wanhose/cookie-dialog-monster/releases/ we see that version 7.1.5 but no `latest` label?!
> 
> ![not latest](https://private-user-images.githubusercontent.com/18578128/361305376-92bf64b9-4f41-42e0-b554-6d21853d55d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NDc0MjAsIm5iZiI6MTcyNDY0NzEyMCwicGF0aCI6Ii8xODU3ODEyOC8zNjEzMDUzNzYtOTJiZjY0YjktNGY0MS00MmUwLWI1NTQtNmQyMTg1M2Q1NWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA0Mzg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2OTZjMGIxNTYzNTUwZmI5ZTA2ZDQ2ZjU5ZjU2YWE4ZGYyYTExZDg1Y2YwMjQ4MDRkN2RkYmE1ZjZjZDJlMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dRtAJcU5sK5GY_0vT_Khu_7Az7Dc7OT_1-7iP8ETiH0)

It was an error, you should see it as stable now. The thing is due summer all the reviews from stores to publish addons are taking longer.

So, please be patient 🙏🏻
