### ISSUE TITLE
erzgebirgskreis.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#798]
#### Browser
Firefox (129.0)
#### Reason
Page contains visual glitches
#### URL
https://www.erzgebirgskreis.de/
#### Version
7.1.4

**Comment by Starfiresg1** [comment]
1. popup-menus on hover at top of the page appear behind main page elements and are therefore not usable
2. entire page displays in black/white

**Comment by wanhose** [comment]
Hi @Starfiresg1,

Thanks for your first issue, and welcome to the community. This issue is addressed in database version `>= 1723669853791`. Please update your database locally and try again.

Have a good day 😉
