### ISSUE TITLE
The reporting dialog should show the full URL that is reported and should allow shortening it

### ISSUE THREAD

**Issue by cremor** [wanhose/cookie-dialog-monster#799]
The current page URL might contain confidental data, or data that you don't want to share for any reason. The reporting dialog should make it clear which URL will be posted on GitHub, and allow the user to shorten it.

**Comment by wanhose** [comment]
Hi @cremor,

This is really important, it has the highest priority for the next release.

Will keep you posted, thanks for the feedback! 💯

**Comment by wanhose** [comment]
This task is scheduled for the next major release, version `7.2.0`, which will be available on September 1st 📅

**Comment by wanhose** [comment]
Hi guys,

One day before... this feature is ready, so please update (or wait a bit to get the update automatically, if you have installed this extension through some store because is under review) to the latest `7.2.0`.

Thanks for your big contribution, more privacy from now on! 🕵️

**Comment by cremor** [comment]
Looks like this doesn't work as expected. I just reported #890 and the report dialog didn't show any query parameters for the URL (so it only showed https://support.github.com/contact/report-abuse). Therefore I didn't change it. But the created GitHub issue again contains the full URL including query parameters.

**Comment by wanhose** [comment]
> Looks like this doesn't work as expected. I just reported #890 and the report dialog didn't show any query parameters for the URL (so it only showed https://support.github.com/contact/report-abuse). Therefore I didn't change it. But the created GitHub issue again contains the full URL including query parameters.

Hi @cremor,

Thanks for reporting again, you were right. There's an issue when reporting that is sending the full URL. I already fixed it, so I will upload a new version as soon as `7.2.3` gets deployed in the different stores.

Sorry for the inconveniences once again 😓

**Comment by wanhose** [comment]
Hi @cremor, 

Try now with version `7.2.4`.
