### ISSUE TITLE
computerbase.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#805]
#### Browser
Firefox (129.0)
#### Reason
Page contains visual glitches
#### URL
https://www.computerbase.de/2024-07/pocketbook-inkpad-eo-test/
#### Version
7.1.4

**Comment by cremor** [comment]
I've also noticed this today. The page has all its content blurred when cookies are not accepted. But with this addon enabled the cookie dialog is automatically hidden while the page is still blurred.

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Firefox (131.0)
#### 📝 Reason
URLs cannot be clicked with this addon enabled.
#### 🔗 URL
https://www.computerbase.de/forum/threads/telefon-uber-wlan-mit-fritzbox-verbinden.1708074/
#### 🏷️ Version
7.2.2

**Comment by wanhose** [comment]
> ## Issue information
> #### 🖥️ Browser
> Firefox (131.0)
> 
> #### 📝 Reason
> URLs cannot be clicked with this addon enabled.
> 
> #### 🔗 URL
> https://www.computerbase.de/forum/threads/telefon-uber-wlan-mit-fritzbox-verbinden.1708074/
> 
> #### 🏷️ Version
> 7.2.2

https://github.com/user-attachments/assets/edb39ba8-d44d-466f-ad55-ea1f3b02c971

Can't reproduce the issue here with the latest version `7.2.4`. Please, update your extension and try again. Feel free to add more information.
