### ISSUE TITLE
amazon.es (cookie dialogue showing)

### ISSUE THREAD

**Issue by alleluia20** [wanhose/cookie-dialog-monster#807]
I have just installed this extension (Cookie Dialog Monster) on Kiwi Browser on Android. It looks great! Unfortunately, I came across a site where the extension is not working.

The web is the Spanish site of Amazon: amazon.es. The cookie dialogue is showing **in both the mobile and desktop sites**.

Thank you in advance.

**Comment by wanhose** [comment]
Hi @alleluia20,

This issue was fixed in `7.2.2`, so please update your extension. I've also added auto-updates from `7.2.1` so you won't need to do this anymore.

Thanks for the report! 👋
