### ISSUE TITLE
pullup-dip.shipping-portal.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#817]
#### Browser
Chrome (126.0.0.0)
#### Reason
Popup showed up
#### URL
https://pullup-dip.shipping-portal.com/rp/?adb_sid=20b665ce-b575-4107-8a1a-1f87158335e8&ref=7e94%2Ffullscreen%2Fm%3Dand%26q%3DSpringseil
#### Version
7.1.4

**Comment by wanhose** [comment]
This is another case where the element isn't mutating itself, it's part of another element and that's why the element is not found.

**Comment by sonnyxq** [comment]
@wanhose Hi there.
Thank you for working on this website becaue I reported it.
I noticed its marked as complete now 2 days ago and went ahead and tried it out with the link above. 
Went ahead with newest version today 7.2.4 with newest database and opened it with Incognito to be sure.
No other extensions are active.
Any idea please why the pop-up is still there?

![Screenshot 2024-09-12 235443](https://github.com/user-attachments/assets/d3b8b015-8b75-4e02-94cf-586ade30a0a2)

**Comment by wanhose** [comment]
> @wanhose Hi there. Thank you for working on this website becaue I reported it. I noticed its marked as complete now 2 days ago and went ahead and tried it out with the link above. Went ahead with newest version today 7.2.4 with newest database and opened it with Incognito to be sure. No other extensions are active. Any idea please why the pop-up is still there?
> 
> ![Screenshot 2024-09-12 235443](https://private-user-images.githubusercontent.com/60904977/367072274-d3b8b015-8b75-4e02-94cf-586ade30a0a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzg3NzksIm5iZiI6MTcyNjE3ODQ3OSwicGF0aCI6Ii82MDkwNDk3Ny8zNjcwNzIyNzQtZDNiOGIwMTUtOGI3NS00ZTAyLTk0Y2YtNTg2YWRlMzBhMGEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIyMDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3NzJlNjYyM2U3YTk3MzkyZGZmMGMxYzU5ZTcyOTFkYTg1YWFmYzM0MzA3MTJjMWFiNWJkMDljOThjYTMyNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xqF7ghFdfc3DKOlhpQsOytdhS-HsHsXaVId0R-vkmxw)

Hi @sonnyxq,

It seems that they changed the structure of the page, so the selector is failing. Let me have a look closer soon.

Sorry for the inconveniences 🙏

**Comment by wanhose** [comment]
Hi @sonnyxq,

Please, update your database version to `>= 1726393512674`.

Thanks! 🥇
