### ISSUE TITLE
cd.cz

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#827]
#### Browser
Firefox (130.0)
#### Reason
Popup showed up
#### URL
https://www.cd.cz/
#### Version
7.1.0

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Firefox (130.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://www.cd.cz/
#### 🏷️ Version
7.1.5.1

**Comment by dreirund** [comment]
When opening in the background and then switching to the tab, the popup is shown:

---

![image](https://github.com/user-attachments/assets/2303d2eb-a4e7-42ce-b2b4-772e0fb98f5b)

---

**Comment by wanhose** [comment]
Hi @dreirund,

This isn't happening anymore with `7.2.2`. Please, update to the latest version.

Thanks for the feedback! 🥇

**Comment by dreirund** [comment]
> *This isn't happening anymore with `7.2.2`. Please, update to the latest version.*

Actually, when I first opened in a background tab, the popup was still there.

Reloading and it went away.

So "halfway fixed" only?
