### ISSUE TITLE
rki.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#831]
#### Browser
Firefox (130.0)
#### Reason
Popup showed up
#### URL
https://www.rki.de/DE/Home/homepage_node.html
#### Version
7.1.0

**Comment by wanhose** [comment]
This is another case where the element isn't mutating itself, it's part of another element and that's why the element is not found.

**Comment by dreirund** [comment]
The (not anymore maintained) "[I still don't care about cookies](https://github.com/OhMyGuus/I-Still-Dont-Care-About-Cookies)" hides the cookie banner succesfully in this site.

Maybe have a look there?

Regards!

**Comment by wanhose** [comment]
Hey @dreirund,

It wasn't very helpful this time, the issue here was there weren't DOM mutations (like the popup showing up) that the extension could handle. So I needed to force it. Please, update your extension to `>= 7.2.2` and the database to `>= 1725175443584`.

Thanks again for your collaboration! 😄

**Comment by dreirund** [comment]
> *Please, update your extension to `>= 7.2.2` and the database to `>= 1725175443584`.*

I can confirm that it is fixed now.
