### ISSUE TITLE
[medizinfuchs.de] Report website dialogue of the addon does not show.

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#832]
Ahoj,

trying to report an issue "Popup shows up" via the addon's context menu for [www.medizinfuchs.de](https://www.medizinfuchs.de/) just results in the screen going gray, but the reporting dialogue of the addon does not show.

On other tabs for other sites it shows.

System:

* Firefox version 130.0b8
* Addon version 7.1.0

Below a screenshot of the site in the state that I want to report the dialogue.

Also happens when I manually acknowledge the dialogue (rejecting optional cookies) and then want to report.

---

![image](https://github.com/user-attachments/assets/3ae272be-6107-4fd2-9cac-190d2e977d7c)

---

Please _also_ consider this as a website report of showing up cookie selection popup.

Regards!

**Comment by wanhose** [comment]
Hi @dreirund,

The issue about the cookie dialog consent should be fixed with database version >= `1724439192806`. I'm working on the report dialog issue.

Thanks for the feedback!

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Chrome (128.0.0.0)
#### 📝 Reason

              Popup showed up
            
#### 🔗 URL
https://www.medizinfuchs.de/
#### 🏷️ Version
7.2.0
