### ISSUE TITLE
technopolis.bg

### ISSUE THREAD

**Issue by Rusenche** [wanhose/cookie-dialog-monster#842]
Hi my friend @wanhose

I ran into a strange problem that I'm sure is caused by your remarkable `Cookie dialog monster` extension.

Steps to reproduce the issue:

1. Open https://www.technopolis.bg/en/Smartfoni-i-mobilni-telefoni/Smartfon-GSM--SAMSUNG-GALAXY-S24-ULTRA-S928-VIOLET/p/503274

2. If the `ADD TO CART` button is pressed

![hh](https://github.com/user-attachments/assets/a3505479-1ab9-4adf-8f2e-b2102299a390)

**then a purchase selection will appear. But the trash button is not functional and it is not possible to delete the placed order.**

![hh1](https://github.com/user-attachments/assets/6b1cc3b0-bc27-49ff-b371-529c9f7b7a59)

Only by turning off the `Cookie dialog monster` extension is this possible.

**Comment by wanhose** [comment]
> Hi my friend @wanhose
> 
> I ran into a strange problem that I'm sure is caused by your remarkable `Cookie dialog monster` extension.
> 
> Steps to reproduce the issue:
> 
> 1. Open https://www.technopolis.bg/en/Smartfoni-i-mobilni-telefoni/Smartfon-GSM--SAMSUNG-GALAXY-S24-ULTRA-S928-VIOLET/p/503274
> 2. If the `ADD TO CART` button is pressed
> 
> ![hh](https://private-user-images.githubusercontent.com/18578128/361148225-a3505479-1ab9-4adf-8f2e-b2102299a390.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTI4ODcsIm5iZiI6MTcyNDU5MjU4NywicGF0aCI6Ii8xODU3ODEyOC8zNjExNDgyMjUtYTM1MDU0NzktMWFiOS00YWRmLThmMmUtYjIxMDIyOTlhMzkwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDEzMjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMWUyZWNhYjRkMTgzZGY0ZmIwYjM4NTRiZjNiNTIwNGRjMDA2OTVmN2EyYjRjNDIxMzMzMzYwMWEzZDc4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mwSO80IRb-4qNc4nIROSMcLNqV0OL6KodEopxupGpXc)
> 
> **then a purchase selection will appear. But the trash button is not functional and it is not possible to delete the placed order.**
> 
> ![hh1](https://private-user-images.githubusercontent.com/18578128/361148258-6b1cc3b0-bc27-49ff-b371-529c9f7b7a59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTI4ODcsIm5iZiI6MTcyNDU5MjU4NywicGF0aCI6Ii8xODU3ODEyOC8zNjExNDgyNTgtNmIxY2MzYjAtYmMyNy00OWZmLWIzNzEtNTI5YzlmN2I3YTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI1VDEzMjk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhM2FkMWQ5NWI0YWZmYzJlNjU3MWYzZjZjOGZmZGVhZGQ1MWEzZTE2MWQ1YjAyZmI2NTMwYTYyZWZhNjdkZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CF9DQ_HfUZvFWf-8BdtlzFr7pL73mOkORx9D-HnSZCs)
> 
> Only by turning off the `Cookie dialog monster` extension is this possible.

Hey @Rusenche,

Happy to see you around the project. I've uploaded a fix so this should be fixed with database version `>= 1724592836220`.

Thanks for your feedback again! 🥇
