### ISSUE TITLE
[Feature suggestion] Add automatic update from github hosted build for your firefox addon.

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#847]
It is indeed possible to [specify custom update check URLs for firefox addons](https://github.com/wanhose/cookie-dialog-monster/issues/618#issuecomment-2212447149).

I hereby suggest this feature to be built into the addon.

I have seen this for other addons, and searching I found a relevant discussion [&nearr;&hairsp;here](https://discourse.mozilla.org/t/what-to-put-under-update-link-for-self-hosted-addon/96893), which points to [&nearr;&hairsp;here](https://extensionworkshop.com/documentation/publish/self-distribution/) (see 2nd bullet point), which in turn points to [&nearr;&hairsp;here](https://extensionworkshop.com/documentation/manage/updating-your-extension/).

Regards!

**Comment by wanhose** [comment]
Hey @dreirund,

I think from now on, this problem should be fixed. I have implemented this `updates.json`, so if you update to the latest `7.2.0` manually... IMO will be the last time you update manually.

Thanks, it was really easy so sorry for the delay. Let's iterate on this, if any issues drop here a message! 🙏
