### ISSUE TITLE
[Feature suggestion] add built "binaries" to the releases.

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#848]
Ahoj,

Feature suggestion:

Since you build the firefox addon anyway, available at [`https://www.cookie-dialog-monster.com/releases/latest.xpi`](https://www.cookie-dialog-monster.com/releases/latest.xpi) &mdash; can you also add the respective `.xpi` file (and maybe also the built chrome addon files?) to the [individual releases](https://github.com/wanhose/cookie-dialog-monster/releases)? Besides making it easier to explicitls download a specific version (and get the correct filename as another side effect), it might be one step to build in [automatic update with firefox](https://github.com/wanhose/cookie-dialog-monster/issues/847).

Regards!

**Comment by wanhose** [comment]
Hi @dreirund,

I added the binaries to all the releases (since I publish the binaries in the web, so since `7.0.4`. I will do it from now on!

Thanks for your valuable feedback 😄
