### ISSUE TITLE
drive.google.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#869]
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
Page contains visual glitches
#### 🔗 URL
https://drive.google.com/drive/my-drive
#### 🏷️ Version
7.1.4

**Comment by sonnyxq** [comment]
Hi there. If I try to open a video file (for example .mp4) which is uploaded on Google Drive. I cant stream it there because of the extension. The extension shows in grey number 1. Seems like it blocked something. After its disabled - everything work fine.

Enabled extension:
![Screenshot 2024-08-30 230128](https://github.com/user-attachments/assets/cb056666-f305-4b17-ac7e-3073af6d56ee)

Disabled extension:
![Screenshot 2024-08-30 230200](https://github.com/user-attachments/assets/8d56e6b5-458f-43e3-b25d-22b8ae31cd59)

**Comment by wanhose** [comment]
> Hi there. If I try to open a video file (for example .mp4) which is uploaded on Google Drive. I cant stream it there because of the extension. The extension shows in grey number 1. Seems like it blocked something. After its disabled - everything work fine.
> 
> Enabled extension: ![Screenshot 2024-08-30 230128](https://private-user-images.githubusercontent.com/60904977/363325764-cb056666-f305-4b17-ac7e-3073af6d56ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTI5NTcsIm5iZiI6MTcyNTA5MjY1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjMzMjU3NjQtY2IwNTY2NjYtZjMwNS00YjE3LWFjN2UtMzA3M2FmNmQ1NmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDA4MjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMGE3ZWE4ZDIyYTliMGVjMDE3YWUzMDA2NWYzMTIwNTU5MzYzNjE2ZTRmYWU0ZDIxOTA3YjU5ZTk4N2NmNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dJDMHN6dFy28OOdctbChRdPQz6fvkpUT4c5nf_aBeYc)
> 
> Disabled extension: ![Screenshot 2024-08-30 230200](https://private-user-images.githubusercontent.com/60904977/363325792-8d56e6b5-458f-43e3-b25d-22b8ae31cd59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTI5NTcsIm5iZiI6MTcyNTA5MjY1NywicGF0aCI6Ii82MDkwNDk3Ny8zNjMzMjU3OTItOGQ1NmU2YjUtNDU4Zi00M2UzLWIyNWQtMjJiOGFlMzFjZDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDA4MjQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NDY0ZDkxNjYxYzRmMDJkZTcwY2MzZGVhMDExNTkwZTRjOGE3MjMyZDA0YzllMjI3YzM0YzU3MTkwZWJlNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EtvKHUtQ0dJ9_bAqkV-LaKFea2b7NEpYocvyY8sKeJM)

Hi @sonnyxq,

Thanks to your report we have fixed several wrong selectors in the database. So if you update your database to `>= 1724667758858` this problem should be fixed already.

Thanks for your valuable contribution 🎖️
