### ISSUE TITLE
okcupid.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#889]
#### 🖥️ Browser
Firefox (130.0)
#### 📝 Reason
After login, site cannot be interacted with when the extension is enabled.
#### 🔗 URL
https://www.okcupid.com/discover
#### 🏷️ Version
7.2.2

**Comment by wanhose** [comment]
Hi,

Can't register today, an error in one of the final steps is blocking me from fixing this issue. Will try again soon. If you can register a test user and give me its credentials, I would be very grateful.

Thanks anyway for your feedback.

**Comment by dreirund** [comment]
> *Can't register today, an error in one of the final steps is blocking me from fixing this issue.*

Can it help to send you the source code of the website when the issue appears?

I think registering a test user is not worth the work (I think it needs a phone number for SMS).

**Comment by dreirund** [comment]
Anyway, I by myself cannot reproduce this issue (right now?).

**Comment by wanhose** [comment]
> > _Can't register today, an error in one of the final steps is blocking me from fixing this issue._
> 
> Can it help to send you the source code of the website when the issue appears?
> 
> I think registering a test user is not worth the work (I think it needs a phone number for SMS).

I tried, but they seem to block fake numbers to receive confirmation messages. I used them sometimes, they usually work but not in this page.

Regarding sending me the source code, if you see the issue again please do it. You aren't seeing it anymore probably because you already accepted it, or because you logged in a couple of times and they accept it for you. Try to clean cache, cookies, application data and try again. 

<img width="657" alt="image" src="https://github.com/user-attachments/assets/59ac7a6f-fd61-4774-9664-78d08590e8a7">

**Comment by wanhose** [comment]
Closing this issue due inactivity, no updates after 1 month ⏳
