### ISSUE TITLE
support.github.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#890]
#### 🖥️ Browser
Firefox (130.0)
#### 📝 Reason
The cookie popup is correctly blocked. But the layout of the site is broken in the process. The section that should be at the very bottom of the page is now instead fixed at the position that is the bottom of the visible scroll area at the time the site is loaded. This causes it to overlap actual site content. The problem  is only visible if the site is long enough to have a scroll bar. In this specific case you'd have to open the site by starting a report process for a GitHub user, only then it will contain enough content to have a scroll bar. An alternative site that shows the same problem immediately is https://wirtschaftscompass.at
#### 🔗 URL
https://support.github.com/contact/report-abuse?category=report-abuse&report=ckadluba&report_id=10721825&report_type=user
#### 🏷️ Version
7.2.2

**Comment by dreirund** [comment]
> *The section that should be at the very bottom of the page is now instead fixed at the position that is the bottom of the visible scroll area at the time the site is loaded. This causes it to overlap actual site content. The problem is only visible if the site is long enough to have a scroll bar. In this specific case you'd have to open the site by starting a report process for a GitHub user*
> *\[&hellip;\]*
> *https://support.github.com/contact/report-abuse?category=report-abuse&report=ckadluba&report_id=10721825&report_type=user*

I can reproduce this:

---

![image](https://github.com/user-attachments/assets/f0e76f8b-8f4d-4823-aef5-8ff74ed8ac34)

**Comment by dreirund** [comment]
> *@[wanhose](https://github.com/wanhose) wanhose closed this as [completed](https://github.com/wanhose/cookie-dialog-monster/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [1 hour ago](https://github.com/wanhose/cookie-dialog-monster/issues/890#event-14164984597)*

I can confirm.

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Chrome (128.0.0.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://support.github.com/contact/report-abuse?category=report-abuse&report=ckadluba&report_id=10721825&report_type=user
#### 🏷️ Version
7.2.4

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Chrome (128.0.0.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://support.github.com/contact/report-abuse?category=report-abuse&report=ckadluba&report_id=10721825&report_type=user
#### 🏷️ Version
7.2.4

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Chrome (128.0.0.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://support.github.com/contact/report-abuse?category=report-abuse&report=ckadluba&report_id=10721825&report_type=user
#### 🏷️ Version
7.2.4
