### ISSUE TITLE
taz.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#892]
#### 🖥️ Browser
Firefox (115.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://taz.de/
#### 🏷️ Version
7.2.2

**Comment by AmrElabbasy** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by wanhose** [comment]
Can't reproduce the issue here, it seems related to [this](https://github.com/wanhose/cookie-dialog-monster/issues/863#issuecomment-2340041126). Please, update your browser to a newer version.
