### ISSUE TITLE
mail.google.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#912]
#### 🖥️ Browser
Firefox (130.0)
#### 📝 Reason
Le popup est apparu
#### 🔗 URL
https://mail.google.com/mail/u/0/#inbox
#### 🏷️ Version
7.2.3

**Comment by k3lteris** [comment]
Sorry for the wrong URL, the true one is https://olympics.com/
The popup for reporting never opened on the Olympics website…

**Comment by wanhose** [comment]
> Sorry for the wrong URL, the true one is https://olympics.com/ The popup for reporting never opened on the Olympics website…

Hi @k3lteris,

Thanks for the issue and welcome to the project. That page is disabled intentionally due some issues with the login part that doesn't work without accepting them. Read more [here](https://github.com/wanhose/cookie-dialog-monster/issues/673).

So no action is expected from our side, you will see always the extension disabled. There are some limitations about the creation of the menu options that will keep appearing even with this condition. So that's the reason why the report dialog doesn't show up.

Thanks anyway and keep reporting! 🕵️

**Comment by k3lteris** [comment]
Other topic read, thanks for the answer. :)
