### ISSUE TITLE
francetvinfo.fr self-hosted videos don't start

### ISSUE THREAD

**Issue by k3lteris** [wanhose/cookie-dialog-monster#914]
🖥️ Browser
Firefox (130.0) 64 bits

📝 Reason
The video within the page doesn't start
Tested on a fresh profile with only Cookie Dialog Monster installed
Excluding the domain francetvinfo.fr then deleting all the cookies and refreshing the page doesn't work
Moreover, the consent popup doesn't appear despite the exclusion of the domain and the cookies removal
Disabling the add-on works (fortunately): the consent popup appears, and the video can start
No problem with third-party/iframes videos

🔗 URL
https://www.francetvinfo.fr/jeux-paralympiques/athletisme/video-le-destin-cruel-de-l-espagnole-elena-congost-disqualifiee-du-marathon-paralympique-apres-le-trebuchement-de-son-guide_6770140.html

🏷️ Version
7.2.3

**Comment by k3lteris** [comment]
Same behaviour on Android with Kiwi Browser and the same version of the add-on

**Comment by wanhose** [comment]
> 🖥️ Browser Firefox (130.0) 64 bits
> 
> 📝 Reason The video within the page doesn't start Tested on a fresh profile with only Cookie Dialog Monster installed Excluding the domain francetvinfo.fr then deleting all the cookies and refreshing the page doesn't work Moreover, the consent popup doesn't appear despite the exclusion of the domain and the cookies removal Disabling the add-on works (fortunately): the consent popup appears, and the video can start No problem with third-party/iframes videos
> 
> 🔗 URL https://www.francetvinfo.fr/jeux-paralympiques/athletisme/video-le-destin-cruel-de-l-espagnole-elena-congost-disqualifiee-du-marathon-paralympique-apres-le-trebuchement-de-son-guide_6770140.html
> 
> 🏷️ Version 7.2.3

Hi @k3lteris,

I've just found the issue, it's a script that needs to load even if you don't accept the cookies. I'm going to try to inject it in the page, but I will need to release a new version this week.

I will keep you posted! 👍

**Comment by k3lteris** [comment]
Disable the extension to accept or reject the cookies, then re-enable the extension, isn't enough: any self-hosted video can't be launched when the extension is enabled
Tested with all cookies accepted ("tout accepter") or rejected ("continuer sans accepter")
Excluding the domain has no effect too, whatever the cookies
