### ISSUE TITLE
linksnappy.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#916]
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
Issue with pop-up blocking
#### 🔗 URL
https://linksnappy.com/home#Login
#### 🏷️ Version
7.2.2

**Comment by sonnyxq** [comment]
Hi there. Please take a look at my .GIF

![Animation1](https://github.com/user-attachments/assets/a7f64be5-ba9d-4f86-b7c9-4ec4a3707dfa)

**Comment by wanhose** [comment]
> Hi there. Please take a look at my .GIF
> 
> ![Animation1](https://private-user-images.githubusercontent.com/60904977/365472497-a7f64be5-ba9d-4f86-b7c9-4ec4a3707dfa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTgyMDIsIm5iZiI6MTcyNTkxNzkwMiwicGF0aCI6Ii82MDkwNDk3Ny8zNjU0NzI0OTctYTdmNjRiZTUtYmE5ZC00Zjg2LWI3YzktNGVjNGEzNzA3ZGZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDIxMzgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNWI5YWNiZjU3MGE0NzMxZmRiYjllZDk5MGE4NzBmZDkxMjNmZTU4NzhiMTNkZmRlZWEwYjIzYTAyNGU0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iy-9v3Qi0FvAu4MbAvxAwpg-YGqZ1iEPZja6KnODZP0) [ ![Animation1](https://private-user-images.githubusercontent.com/60904977/365472497-a7f64be5-ba9d-4f86-b7c9-4ec4a3707dfa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTgyMDIsIm5iZiI6MTcyNTkxNzkwMiwicGF0aCI6Ii82MDkwNDk3Ny8zNjU0NzI0OTctYTdmNjRiZTUtYmE5ZC00Zjg2LWI3YzktNGVjNGEzNzA3ZGZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDIxMzgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNWI5YWNiZjU3MGE0NzMxZmRiYjllZDk5MGE4NzBmZDkxMjNmZTU4NzhiMTNkZmRlZWEwYjIzYTAyNGU0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iy-9v3Qi0FvAu4MbAvxAwpg-YGqZ1iEPZja6KnODZP0) ](https://private-user-images.githubusercontent.com/60904977/365472497-a7f64be5-ba9d-4f86-b7c9-4ec4a3707dfa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTgyMDIsIm5iZiI6MTcyNTkxNzkwMiwicGF0aCI6Ii82MDkwNDk3Ny8zNjU0NzI0OTctYTdmNjRiZTUtYmE5ZC00Zjg2LWI3YzktNGVjNGEzNzA3ZGZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDIxMzgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNWI5YWNiZjU3MGE0NzMxZmRiYjllZDk5MGE4NzBmZDkxMjNmZTU4NzhiMTNkZmRlZWEwYjIzYTAyNGU0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iy-9v3Qi0FvAu4MbAvxAwpg-YGqZ1iEPZja6KnODZP0) [ ](https://private-user-images.githubusercontent.com/60904977/365472497-a7f64be5-ba9d-4f86-b7c9-4ec4a3707dfa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5MTgyMDIsIm5iZiI6MTcyNTkxNzkwMiwicGF0aCI6Ii82MDkwNDk3Ny8zNjU0NzI0OTctYTdmNjRiZTUtYmE5ZC00Zjg2LWI3YzktNGVjNGEzNzA3ZGZhLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDIxMzgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhNWI5YWNiZjU3MGE0NzMxZmRiYjllZDk5MGE4NzBmZDkxMjNmZTU4NzhiMTNkZmRlZWEwYjIzYTAyNGU0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Iy-9v3Qi0FvAu4MbAvxAwpg-YGqZ1iEPZja6KnODZP0)

Hi @sonnyxq,

Try again with database version `>= 1725917999552`.

Sorry for the inconveniences 🙏

**Comment by wanhose** [comment]
## Issue information
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
cookie pop-up at the bottom of the page.
#### 🔗 URL
https://linksnappy.com/home
#### 🏷️ Version
7.3.0

**Comment by sonnyxq** [comment]
![Screenshot 2024-09-21 012344](https://github.com/user-attachments/assets/3918b52c-c4ff-40f2-bea5-09a8eaf27c24)

**Comment by wanhose** [comment]
> ![Screenshot 2024-09-21 012344](https://private-user-images.githubusercontent.com/60904977/369573009-3918b52c-c4ff-40f2-bea5-09a8eaf27c24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTU1MDgsIm5iZiI6MTcyNzY5NTIwOCwicGF0aCI6Ii82MDkwNDk3Ny8zNjk1NzMwMDktMzkxOGI1MmMtYzRmZi00MGYyLWJlYTUtMDlhOGVhZjI3YzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDExMjAwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMDZhZTFiMzRmMDA1MTVlNjBhNjdjOTI5NzRhOWU1MTIzYzE3YjdlM2JjYzMzZTNhYjg0MGU3MDIwNTFjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2mo0d83zc_TZVi92lI9ueYThlHwPSg_2kG6hii5okHM)

Hi @sonnyxq,

Please, update to database version `>= 1727695307027`.

Thanks!
