### ISSUE TITLE
login.teamviewer.com

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#919]
#### 🖥️ Browser
Firefox (115.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://login.teamviewer.com/LogOn
#### 🏷️ Version
7.2.3

**Comment by NobleTwo** [comment]
Update: Popup does not appear for Firefox 128.2.0esr.

**Comment by wanhose** [comment]
> Update: Popup does not appear for Firefox 128.2.0esr.

Hi @NobleTwo,

I'm going to check what's the minimum version for this extension to work correctly in Firefox, because the `web-ext` package says `113.x` but it doesn't seem to be true 😅 

Thanks for the confirmation, closing the issue 💯
