### ISSUE TITLE
Website reporting dialogue does not show cursor.

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#924]
* Browser: Firefox,
* addon version: 7.2.3,
* issue: There is no cursor shown in the website reporting dialogue's text input field.

**Comment by wanhose** [comment]
> * Browser: Firefox,
> * addon version: 7.2.3,
> * issue: There is no cursor shown in the website reporting dialogue's text input field.

Hi @dreirund,

Can you add more information or screenshots? I don't see a link to the page neither.

Thanks in advance!

**Comment by dreirund** [comment]
> *Can you add more information or screenshots?*

I just tried to make a screenshot; now I have addon version 7.2.4 and when I right click there on the addon icon I see Firefox' context menu for the addon (manage extension and so on) but not anymore "report website".

Description: When I use the addon's feature to report a website, the addon opens a dialogue. The text field of the dialogue is editable, but no text cursor at all is visible.

> *I don't see a link to the page neither.*

It is generic.

**Comment by wanhose** [comment]
> > _Can you add more information or screenshots?_
> 
> I just tried to make a screenshot; now I have addon version 7.2.4 and when I right click there on the addon icon I see Firefox' context menu for the addon (manage extension and so on) but not anymore "report website".
> 
> Description: When I use the addon's feature to report a website, the addon opens a dialogue. The text field of the dialogue is editable, but no text cursor at all is visible.
> 
> > _I don't see a link to the page neither._
> 
> It is generic.

Understood, I was able to reproduce the issue. Seems something related to the stylesheet in Mozilla Firefox. It's annoying, but you can write in it yet.

**Comment by dreirund** [comment]
> *Can you add [...] screenshots?*

Now here:

---

![image](https://github.com/user-attachments/assets/5a15c00c-1240-4de3-994b-62bc01c4d9f0)

**Comment by wanhose** [comment]
> > _Can you add [...] screenshots?_
> 
> Now here:
> 
> ![image](https://private-user-images.githubusercontent.com/1590519/366199717-5a15c00c-1240-4de3-994b-62bc01c4d9f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5OTkyNzgsIm5iZiI6MTcyNTk5ODk3OCwicGF0aCI6Ii8xNTkwNTE5LzM2NjE5OTcxNy01YTE1YzAwYy0xMjQwLTRkZTMtOTk0Yi02MmJjMDFjNGQ5ZjAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMjAwOTM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTMwODUxNDJhMGU2ZjgyNTIzZTRiMWFmNmMwN2YxMWYyOWViYmJkY2I4NWEyZmZjOTA5NTBhYTI1ODE3YTRmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EXJg9lRVTSjqEobTq_b-cdDi7ABSksy5fsY_Vwc8_Ms)

Is that a line crossing the button? Is the dialog layout broken? Or is it something related to the screenshot?

**Comment by dreirund** [comment]
On Tue, 10 Sep 2024 13:20:23 -0700, wanhose ***@***.***>
wrote:

> Is that a line crossing the button? Is the dialog layout broken? Or
> is it something related to the screenshot?

Related to the screenshot.

**Comment by wanhose** [comment]
> On Tue, 10 Sep 2024 13:20:23 -0700, wanhose ***@***.***> wrote: Is that a line crossing the button? Is the dialog layout broken? Or is it something related to the screenshot?
> Related to the screenshot

Hi @dreirund,

This should have been fixed with `7.2.5`. Please, update to this version and try again.

Thanks for the feedback! 🎖️

**Comment by dreirund** [comment]
On Thu, 12 Sep 2024 12:11:19 -0700, wanhose ***@***.***>
wrote:

> This should have been fixed with `7.2.5`.

Correct.

**Comment by wanhose** [comment]
Hi @dreirund,

I've decided to unpublish the `7.2.5` update due some big issues. I suggest you to downgrade your extension even with this issue.

Will keep you posted, sorry for the inconveniences 🙏

**Comment by wanhose** [comment]
Let's try again with version `7.2.6`. Thanks for your patience ❤️

**Comment by wanhose** [comment]
Hi,

I've tried to release something today due the amount of improvements but the changes about using a different property than `display` aren't working well in all browsers. Reverting changes to `7.2.4`. It's late, will schedule a new release for another day.

Please, downgrade to `7.2.4` version again. As this issue is related to the `7.2.6` which isn't available anymore, closing this issue. Have a good night.
