### ISSUE TITLE
Firefox 131.0b3/ Addon 7.2.4: Context menu with "report website" not shown anymore.

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#928]
Firefox version 131.0b3/ Addon version 7.2.4

The functionality to report websites has disappeared from the Addon's context menu.

Instead, on right click, I get Firefox' context menu.

On left click, I do not find any "report website" option.

---

![image](https://github.com/user-attachments/assets/c7747530-5389-4c2c-abea-8be82f89b591)

---

![image](https://github.com/user-attachments/assets/6ae12ecd-fc91-49f1-b5b2-f1686ccee1e2)

---

Regards!

**Comment by wanhose** [comment]
> Firefox version 131.0b3/ Addon version 7.2.4
> 
> The functionality to report websites has disappeared from the Addon's context menu.
> 
> Instead, on right click, I get Firefox' context menu.
> 
> On left click, I do not find any "report website" option.
> 
> ![image](https://private-user-images.githubusercontent.com/1590519/366188605-c7747530-5389-4c2c-abea-8be82f89b591.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5OTc3ODcsIm5iZiI6MTcyNTk5NzQ4NywicGF0aCI6Ii8xNTkwNTE5LzM2NjE4ODYwNS1jNzc0NzUzMC01Mzg5LTRjMmMtYWJlYS04YmU4MmY4OWI1OTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMTk0NDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGIyNmEzNjEyN2E4NjM2MzhkZTE1YTNjY2I3ZjYxMDg0YTMzYjhhOTYyNGQwNGE4ZTdkMjMzZWJhODA5OGU1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hSL-5aF3ORA5pqlcL6AbCyeoEinuFWuxCwBMciMYi-U)
> 
> ![image](https://private-user-images.githubusercontent.com/1590519/366188623-6ae12ecd-fc91-49f1-b5b2-f1686ccee1e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5OTc3ODcsIm5iZiI6MTcyNTk5NzQ4NywicGF0aCI6Ii8xNTkwNTE5LzM2NjE4ODYyMy02YWUxMmVjZC1mYzkxLTQ5ZjEtYjViMi1mMTY4NmNjZWUxZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMTk0NDQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWZhYjA0N2U5ZTdmODNkMzc2Y2UyYTZhYTkwMmVjZjMzN2M4MDFmNWJmOWI5YzM4MWEzNTZhZTM4MzU1Y2U2OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.urDrzIf35bz-xddT-6gufOjudRdajFR0ZXJFAGvFRwM)
> 
> Regards!

Hi @dreirund,

Did you reinstall it manually or something? If so, do you remember the name of the file you downloaded? If it was `latest-mozilla-mobile.xpi`, you downloaded accidentally the mobile version which doesn't have that feature. If that's not the case, can you fully close the browser and open it again? The context menu installation is being done in every browser start.

Looking forward to hear from you about this weird error 😅

**Comment by dreirund** [comment]
On Tue, 10 Sep 2024 12:48:45 -0700, wanhose ***@***.***>
wrote:

> Did you reinstall it manually or something?

If I remember correctly, then it was automatic update.

But I can be wrong.


> If that's not the case, can
> you fully close the browser and open it again?

I have already done that before reporting.

I now manually downloaded and installed [`7.2.4.xpi`](https://github.com/wanhose/cookie-dialog-monster/releases/download/7.2.4/7.2.4.xpi) and the reporting feature is back.
