### ISSUE TITLE
chaos.social

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#931]
#### 🖥️ Browser
Firefox (131.0)
#### 📝 Reason
(After having logged i to Matodo): The "tart" page i trucated.
#### 🔗 URL
https://chaos.social/deck/getting-started
#### 🏷️ Version
7.2.4

**Comment by dreirund** [comment]
> *(After having logged i to Matodo): The "tart" page i trucated.*

Here is a screenshot (personal data censored, that is the gray rectangle):

---

![image](https://github.com/user-attachments/assets/c93dbcab-bc5d-4c84-ad78-37b7da03ca68)

---

When I disable the addon, the start page is shown in full.

**Comment by dreirund** [comment]
> *(After having logged i to Matodo): The "tart" page i trucated.*

For the corrupt text, see issue #932.

**Comment by wanhose** [comment]
> > _(After having logged i to Matodo): The "tart" page i trucated._
> 
> Here is a screenshot (personal data censored, that is the gray rectangle):
> 
> ![image](https://private-user-images.githubusercontent.com/1590519/366367263-c93dbcab-bc5d-4c84-ad78-37b7da03ca68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzMzMDIsIm5iZiI6MTcyNjE3MzAwMiwicGF0aCI6Ii8xNTkwNTE5LzM2NjM2NzI2My1jOTNkYmNhYi1iYzVkLTRjODQtYWQ3OC0zN2I3ZGEwM2NhNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMjAzMDAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmEyMzJjMTQ3ODk3OGE3ZmRiOTdjZGNmZDhlOTk2ZTFmY2U4YmExMmUxY2Y5MTg3YTQyMmE1ZDI0YjVhMmY5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k4KQQ2INhegN8jsSoBZ_rZIl3O8IpuG0ORIqTpxnVWc)
> 
> When I disable the addon, the start page is shown in full.

Hi @dreirund,

Can't reproduce the issue anymore with database version `>= 1726172508025` and extension version `7.2.5`. Please, update and try again.

Thanks for your contribution! 😄
