### ISSUE TITLE
Website report dialogue: Cannot type "s" and "n" characters in reason description field when trying to report https://chaos.social/deck/getting-started.

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#932]
From #931:

> *(After having logged i to Matodo): The "tart" page i trucated.*

I mostly could not type "s" and "n" in the addon's dialogue to describe the issue (after many repeats it worked, but I did it only once for the first "*n*").

Outside that dialogue I could type it.

The text should have read (missing characters I put in bold):

"*(After having logged i**n** to Ma**s**todo**n**): The "**s**tart" page i**s** tru**n**cated.*".

The URL I wanted to report was  
[https://chaos.social/deck/getting-started](https://chaos.social/deck/getting-started)  
after log-in.

Screenshot:

---

![image](https://github.com/user-attachments/assets/8e617430-eaa2-4036-b3f8-a881de2dc29e)

---

* Browser: Firefox 131.0b3 (64-bit) on GNU/Linux,
* Addon version: 7.2.4,
* Database version: 1726001694653.

Maybe you can make it a "real" dialogue, not something that Firefox tries to draw on the website canvas? Actually, I _could_ take a screenshot of your dialogue with a website screenshot tool.

The addon "[I still don't care about cookies](https://github.com/OhMyGuus/I-Dont-Care-About-Cookies)" makes it differently; it seems _not_ to draw it's reporting dialogue on the website canvas, and I never had issues with it's dialogue so far.

**Comment by wanhose** [comment]
> From #931:
> 
> > _(After having logged i to Matodo): The "tart" page i trucated._
> 
> I mostly could not type "s" and "n" in the addon's dialogue to describe the issue (after many repeats it worked, but I did it only once for the first "_n_").
> 
> Outside that dialogue I could type it.
> 
> The text should have read (missing characters I put in bold):
> 
> "_(After having logged i**n** to Ma**s**todo**n**): The "**s**tart" page i**s** tru**n**cated._".
> 
> The URL I wanted to report was https://chaos.social/deck/getting-started after log-in.
> 
> Screenshot:
> 
> ![image](https://private-user-images.githubusercontent.com/1590519/366368796-8e617430-eaa2-4036-b3f8-a881de2dc29e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNjg1ODAsIm5iZiI6MTcyNjE2ODI4MCwicGF0aCI6Ii8xNTkwNTE5LzM2NjM2ODc5Ni04ZTYxNzQzMC1lYWEyLTQwMzYtYjNmOC1hODgxZGUyZGMyOWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTJUMTkxMTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI3MTBhNmE3NWYzZDVjY2YyYzllYjdiNWI1YTRjYjllYTQ3MTZjYzY1OTAyODAxYWQ1ZjAyYjVjNDZmY2YyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.2T3rFT02TUg8g9oWI6XiFX_tQ4Zuf0lYqm4ZF4CR5Q0)
> 
> * Browser: Firefox 131.0b3 (64-bit) on GNU/Linux,
> * Addon version: 7.2.4,
> * Database version: 1726001694653.
> 
> Maybe you can make it a "real" dialogue, not something that Firefox tries to draw on the website canvas? Actually, I _could_ take a screenshot of your dialogue with a website screenshot tool.
> 
> The addon "[I still don't care about cookies](https://github.com/OhMyGuus/I-Dont-Care-About-Cookies)" makes it differently; it seems _not_ to draw it's reporting dialogue on the website canvas, and I never had issues with it's dialogue so far.

Hi @dreirund,

Of course, they are using a different approach which has other disadvantages too. Anyway, this should have been fixed with `7.2.5`. Please, update to this version and try again.

Thanks for the feedback! 🎖️

**Comment by dreirund** [comment]
> *Anyway, this should have been fixed with `7.2.5`.*

Correct.

**Comment by wanhose** [comment]
Hi @dreirund,

I've decided to unpublish the `7.2.5` update due some big issues. I suggest you to downgrade your extension even with this issue.

Will keep you posted, sorry for the inconveniences 🙏

**Comment by wanhose** [comment]
Let's try again with version `7.2.6`. Thanks for your patience ❤️

**Comment by wanhose** [comment]
Hi,

I've tried to release something today due the amount of improvements but the changes about using a different property than `display` aren't working well in all browsers. Reverting changes to `7.2.4`. It's late, will schedule a new release for another day.

Please, downgrade to `7.2.4` version again. As this issue is related to the `7.2.6` which isn't available anymore, closing this issue. Have a good night.
