### ISSUE TITLE
bbc.co.uk - No videos with extension enabled

### ISSUE THREAD

**Issue by AbsenceJam** [wanhose/cookie-dialog-monster#941]
Chrome 128.0.6613.138 
macO S14.6.1 (23G93)

Extension actually disabled, not site whitelisted (which isn't making a difference either way).

For example https://www.bbc.co.uk/news/articles/cjrder972xgo
Extension enabled:
![Screenshot 2024-09-12 at 13 32 06](https://github.com/user-attachments/assets/ae101195-81f5-42e8-8068-cf567568e201)

Extension disabled:
![Screenshot 2024-09-12 at 13 32 15](https://github.com/user-attachments/assets/07ec8d40-f174-4355-8e84-26fdd51be762)

**Comment by wanhose** [comment]
> This extension is the cause of more display issues I've been running into.
> 
> Here's another: https://www.thetvdb.com/search?query=action Enabled: ![Screenshot 2024-09-12 at 16 14 36](https://private-user-images.githubusercontent.com/24455272/366943357-e01be7e6-4c0d-478e-9562-a25d1abc0e69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzY1MjcsIm5iZiI6MTcyNjE3NjIyNywicGF0aCI6Ii8yNDQ1NTI3Mi8zNjY5NDMzNTctZTAxYmU3ZTYtNGMwZC00NzhlLTk1NjItYTI1ZDFhYmMwZTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIxMjM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2OGRhYTc3MTMyNGMxOTYzNGQ4ZjAwYzJhNzBiOTRjMTFhNjg0MTYwYmFhNGZlZGU2OTJlYTU1ODBkYzZiNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2YXTKALx7F9PDBEZQKrdKUFI-hFR__esWO2WKFKhlXI) Disabled: ![Screenshot 2024-09-12 at 16 14 23](https://private-user-images.githubusercontent.com/24455272/366943368-803fc816-9052-4eb3-b973-785fa98c55b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzY1MjcsIm5iZiI6MTcyNjE3NjIyNywicGF0aCI6Ii8yNDQ1NTI3Mi8zNjY5NDMzNjgtODAzZmM4MTYtOTA1Mi00ZWIzLWI5NzMtNzg1ZmE5OGM1NWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDIxMjM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYzY2MjRlYzhhMmVhZDMyZWY0OWE4NjMxZjA4YTRjMTZhNzQwMjVkMTI3YTdjYmY5NWU4NDkwNzUxZGQyZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eMtgw0L2GLs3Y7l8fBBBvmc4qnxt69KpTZkNNSYgUYI)
> 
> Tested both sites with all other extensions disabled.

Hi @AbsenceJam,

Welcome to the project, the issue on tvdb.com should be fixed already with database version `>= 1726174160976`. Regarding the issue on bbc.co.uk, I'd say I can do nothing about it.

Will take a look again soon, sorry for the inconveniences 🙏

**Comment by wanhose** [comment]
Hi @AbsenceJam,

Unfortunately, there's no way to fix the issue about those videos. There are limitations to how I can interact with the page. I can hide elements, but I can't run the scripts responsible for loading videos. My suggestion: either disable the extension for this site and accept their cookies, or better yet, switch to a more trustworthy news website—one that isn’t so devilish about user preferences.

Sorry for the inconveniences, marking this as `wontfix`.
