### ISSUE TITLE
welt.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#966]
#### 🖥️ Browser
Firefox (131.0)
#### 📝 Reason
With the addon enabled, the links to "welt.de" below do not show up.
#### 🔗 URL
https://www.welt.de/vermischtes/video253487600/Livestream-Syrer-wollte-moeglichst-viele-Soldaten-in-deren-Mittagspause-toeten-alle-Entwicklungen.html
#### 🏷️ Version
7.2.4

**Comment by dreirund** [comment]
It are the stuff below "Mehr aus dem Web".

**Comment by wanhose** [comment]
> It are the stuff below "Mehr aus dem Web".

Hi @dreirund,

Unfortunately, there's no way to fix the issue about that section. There are limitations to how I can interact with the page. I can hide elements, but I can't run the scripts responsible for loading sections. My suggestion: either disable the extension for this site and accept their cookies, or better yet, switch to a more trustworthy news website—one that isn't so devilish about user preferences.

Sorry for the inconveniences, marking this as `wontfix`.
