### ISSUE TITLE
Firefox: No automatic update from addon version 7.2.4 to addon version 7.3.0.

### ISSUE THREAD

**Issue by dreirund** [wanhose/cookie-dialog-monster#969]
I have version [7.2.4](https://github.com/wanhose/cookie-dialog-monster/releases/tag/7.2.4) of this addon installed on Firefox 131.0b6.

You have [released](https://github.com/wanhose/cookie-dialog-monster/releases) version [7.3.0](https://github.com/wanhose/cookie-dialog-monster/releases/tag/7.3.0), but the Firefox update does not find any update.

Regards!

**Comment by wanhose** [comment]
Hi @dreirund,

Thanks for the heads up, the Mozilla updates.json file can take up to 24 hours to show up due CDN/cache systems. I just forced to clean the cache. Please, try again.

Sorry for the issues! :sweat_smile:

**Comment by dreirund** [comment]
> *Thanks for the heads up, the Mozilla updates.json file can take up to 24 hours to show up due CDN/cache systems.*

Ah OK, thanks.

Have not thought about that.

Regards!
