### ISSUE TITLE
On some sites (Bing, Amazon, etc), the dialogue keeps on displaying for a moment at all the requests

### ISSUE THREAD

**Issue by alleluia20** [wanhose/cookie-dialog-monster#984]
Hello,

This is strictly not a bug of Cookie Dialog Monster, but I think the extension could consider those cases. Some sites do not accept so easily to have the cookies rejected and, given that we usually visit those sites many times in a row, it is annoying to see the cookie dialogue for a moment (before the extension closes it) so many consecutive times.

Some examples of those sites are:

1) Bing: you briefly see the dialogue every time you do different related searches.
2) Amazon (at least, amazon.es): you briefly see the dialogue every time you visit an item. Actually, one usually sees many items to look at the different possibilities, compare the products, etc.

Maybe the extension should just accept the cookies on those sites or, at least, offer the user the option to do so...

Regards.

**Comment by d4k0** [comment]
I've noticed the same thing on Amazon.de. Even when reloading the same tab, the cookie popup appears every time:

![amazon de_cookie_popup](https://github.com/user-attachments/assets/080e91b4-7ffa-4041-9170-b40f6192119d)

I didn't have this problem with “I still don't care about cookies”. It would be very nice if a solution could be found here, as it is very annoying.

**Comment by wanhose** [comment]
> Hello,
> 
> This is strictly not a bug of Cookie Dialog Monster, but I think the extension could consider those cases. Some sites do not accept so easily to have the cookies rejected and, given that we usually visit those sites many times in a row, it is annoying to see the cookie dialogue for a moment (before the extension closes it) so many consecutive times.
> 
> Some examples of those sites are:
> 
> 1. Bing: you briefly see the dialogue every time you do different related searches.
> 2. Amazon (at least, amazon.es): you briefly see the dialogue every time you visit an item. Actually, one usually sees many items to look at the different possibilities, compare the products, etc.
> 
> Maybe the extension should just accept the cookies on those sites or, at least, offer the user the option to do so...
> 
> Regards.

> I've noticed the same thing on Amazon.de. Even when reloading the same tab, the cookie popup appears every time:
> 
> ![amazon de_cookie_popup](https://private-user-images.githubusercontent.com/10982825/371146386-080e91b4-7ffa-4041-9170-b40f6192119d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTkwNzgsIm5iZiI6MTcyNzY5ODc3OCwicGF0aCI6Ii8xMDk4MjgyNS8zNzExNDYzODYtMDgwZTkxYjQtN2ZmYS00MDQxLTkxNzAtYjQwZjYxOTIxMTlkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDEyMTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNmM4MDA5OGFiYjI3Zjk1ZGQ0NjUxZjA2MzdjY2EzOGM2MTQ3ZTJjM2VmMTQzMDZmZjBmOTNlZGQ3ZDA1NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MOsFo15p6tvJEf_J611sf14mbFm-ExHCrQWFXc8x4iA) [ ![amazon de_cookie_popup](https://private-user-images.githubusercontent.com/10982825/371146386-080e91b4-7ffa-4041-9170-b40f6192119d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTkwNzgsIm5iZiI6MTcyNzY5ODc3OCwicGF0aCI6Ii8xMDk4MjgyNS8zNzExNDYzODYtMDgwZTkxYjQtN2ZmYS00MDQxLTkxNzAtYjQwZjYxOTIxMTlkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDEyMTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNmM4MDA5OGFiYjI3Zjk1ZGQ0NjUxZjA2MzdjY2EzOGM2MTQ3ZTJjM2VmMTQzMDZmZjBmOTNlZGQ3ZDA1NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MOsFo15p6tvJEf_J611sf14mbFm-ExHCrQWFXc8x4iA) ](https://private-user-images.githubusercontent.com/10982825/371146386-080e91b4-7ffa-4041-9170-b40f6192119d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTkwNzgsIm5iZiI6MTcyNzY5ODc3OCwicGF0aCI6Ii8xMDk4MjgyNS8zNzExNDYzODYtMDgwZTkxYjQtN2ZmYS00MDQxLTkxNzAtYjQwZjYxOTIxMTlkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDEyMTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNmM4MDA5OGFiYjI3Zjk1ZGQ0NjUxZjA2MzdjY2EzOGM2MTQ3ZTJjM2VmMTQzMDZmZjBmOTNlZGQ3ZDA1NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MOsFo15p6tvJEf_J611sf14mbFm-ExHCrQWFXc8x4iA) [ ](https://private-user-images.githubusercontent.com/10982825/371146386-080e91b4-7ffa-4041-9170-b40f6192119d.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTkwNzgsIm5iZiI6MTcyNzY5ODc3OCwicGF0aCI6Ii8xMDk4MjgyNS8zNzExNDYzODYtMDgwZTkxYjQtN2ZmYS00MDQxLTkxNzAtYjQwZjYxOTIxMTlkLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDEyMTkzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNmM4MDA5OGFiYjI3Zjk1ZGQ0NjUxZjA2MzdjY2EzOGM2MTQ3ZTJjM2VmMTQzMDZmZjBmOTNlZGQ3ZDA1NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MOsFo15p6tvJEf_J611sf14mbFm-ExHCrQWFXc8x4iA)
> 
> I didn't have this problem with “I still don't care about cookies”. It would be very nice if a solution could be found here, as it is very annoying.

Hi both,

Thank you for bringing up these concerns, and I completely understand how frustrating it can be to see those cookie dialogues repeatedly. However, this is essentially the trade-off when prioritizing performance and user preferences, as our extension does.

Unlike "I Don't Care About Cookies" which bypasses or accepts cookie dialogues without considering the user's preference, Cookie Dialog Monster is designed with a different philosophy: **to preserve your choice** while still removing the annoying cookie pop-ups. This means that when you reload or revisit a page, if the site doesn’t store your preferences effectively, the cookie dialogue will briefly appear. It's worth noting that some websites, such as Amazon or Bing, are quite persistent in showing these pop-ups even after multiple visits, and it’s hard to bypass them entirely without compromising your privacy settings.

As for why the pop-ups briefly appear before being removed for pages opened in the background, this is a result of balancing performance and functionality. You may have noticed this issue reported here #284, where analyzing cookie dialogues too early (in the background or upon page load) caused performance issues for users with many open tabs. To optimize performance, we only analyze and dismiss the dialogues after you are in front of the page, causing that slight delay. While this might be a bit annoying, it's a necessary compromise to ensure the extension runs smoothly across multiple scenarios.

If the occasional pop-up becomes too much of a distraction, you could manually accept the cookies on those sites to stop seeing the dialogue or disable the extension for certain sites where it's more of a hassle. Disable, accept and you won't see them anymore 😄 

<img width="277" alt="image" src="https://github.com/user-attachments/assets/cbf56422-4bf3-4d42-b368-22723e0ae048">

**Comment by wanhose** [comment]
Hi everyone,

I'm working on this, I've already managed to decrease it some milliseconds. But there's still some work to do. As I suggest above, for the moment please accept their cookies if it's too disturbing.

Sorry for the inconveniences.

**Comment by wanhose** [comment]
Hey everyone 👋

I'm excited to announce that version `7.3.2` has just been released! 🎉

This update includes major improvements to address the hiding lag many of you have experienced. We've worked hard on this, and I'm confident it will improve performance for most users. However, for particularly heavy pages, there may still be some occasional lag. I don't think there's more room to improve, so now the maximum delay is `50ms`.

We really appreciate all your contributions and feedback, which have been incredibly helpful in improving the project. 💙

Thank you for being such an awesome and supportive community!

**Comment by alleluia20** [comment]
Thank you very much!

Please do keep so active in this project :-) Other open source projects
(like "I still don't care about cookies") are (or have recently been)
inactive, so you are our only hope :-)

Regards.

**Comment by wanhose** [comment]
> Thank you very much! Please do keep so active in this project :-) Other open source projects (like "I still don't care about cookies") are (or have recently been) inactive, so you are our only hope :-) Regards. Message ID: ***@***.***>
> […](#)

Thank you @alleluia20, honestly... it means a lot to hear that!

Every time we make a small fix, it might improve things on one site but could break it on another. With so many different pages out there (how many pages would you say are out there? 🤣), we're always balancing progress and the risk of causing new issues. It's why updates can take time; it's a careful dance of testing and tweaking. And for many projects, that challenge is what eventually kills them.

But what makes this project different and why it's still going strong is because of the community of contributors like you. It's hard to stay motivated working on something every single day without that support, but knowing that others are as invested as I am is the spark that keeps this alive. Four years in (5 years next March 😮), we're still moving forward, and with each update, we're getting closer to something that works better for everyone.

![Thanks](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExMWdsMzFuaXZpbzA2b2Vja3k4MmhpbWI2eG42bDc1cno2a3J3aGxxciZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ZfK4cXKJTTay1Ava29/giphy.gif)
