### ISSUE TITLE
motointegrator.de

### ISSUE THREAD

**Issue by wanhose** [wanhose/cookie-dialog-monster#985]
#### 🖥️ Browser
Chrome (126.0.0.0)
#### 📝 Reason
Popup showed up
#### 🔗 URL
https://www.motointegrator.de/
#### 🏷️ Version
7.3.0

**Comment by sonnyxq** [comment]
Hi there @wanhose 

This is what I see.

![1](https://github.com/user-attachments/assets/c646c1ed-468a-4ada-af7b-8cf5e5fb9116)

Its not blocked and if I try to interact and modify those coockies. This is what I see.

![2](https://github.com/user-attachments/assets/b56d69e4-93a6-4e58-8b0d-6e7ece17175e)

**Comment by wanhose** [comment]
> Hi there @wanhose
> 
> This is what I see.
> 
> ![1](https://private-user-images.githubusercontent.com/60904977/369532599-c646c1ed-468a-4ada-af7b-8cf5e5fb9116.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MDM0NzMsIm5iZiI6MTcyNzcwMzE3MywicGF0aCI6Ii82MDkwNDk3Ny8zNjk1MzI1OTktYzY0NmMxZWQtNDY4YS00YWRhLWFmN2ItOGNmNWU1ZmI5MTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDEzMzI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlN2M4OTIwZTBiYTAxMzE3NWZkYTk1NmJlNzBiNDMwMDdkYTE4N2YyZThhZDVhZDQyNzg4OGE5ZTY4NDVlZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tDyMZ0Y7Q39TINkeOGTLwBWidn4Kf2Cw1mmgglS4zsY)
> 
> Its not blocked and if I try to interact and modify those cookies. This is what I see.
> 
> ![2](https://private-user-images.githubusercontent.com/60904977/369532816-b56d69e4-93a6-4e58-8b0d-6e7ece17175e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3MDM0NzMsIm5iZiI6MTcyNzcwMzE3MywicGF0aCI6Ii82MDkwNDk3Ny8zNjk1MzI4MTYtYjU2ZDY5ZTQtOTNhNi00ZTU4LThiMGQtNmU3ZWNlMTcxNzVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDEzMzI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZjNjZmY3YzNmZDhiNDRiYTBiYzcxYjgxNzhmMzMzNWFmZjU0MDAwMTY2NDhiZmFmNjQ2YjRjNGNhYmZiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cgDv9KNXmWUz5ryMBQIvtYhg1hPnTvywTenD8-udn9g)

Hi @sonnyxq,

Thanks for the feedback. Please, update to database version `>= 1727702990803`.

Have a good day!
